export type Act2ProjectStoryBeat = {
  id: string;
  title: string;
  image?: string;
  body: string[];
  stage: 1 | 2 | 3 | 4;
};

export const CABIN_CONTRIBUTION_BEATS: Act2ProjectStoryBeat[] = [
  {
    "id": "cabin:01",
    "title": "1/16 · Vi börjar här",
    "image": "/assets/village/story-moments/act2/cabin/renovating-cabin1.png",
    "body": [
      "Ni öppnar stugan ordentligt. Luften står stilla och det luktar damm, trä och gammal sommar.",
      "Barnet: Det luktar konstigt här inne.",
      "Alve: Det luktar stuga.",
      "Barnet: Är stuglukt mest damm?",
      "Alve: Damm, trä… gamla filtar. Och lite så där instängt.",
      "Barnet: Det låter inte som en särskilt bra reklam.",
      "Alve: Du skulle fattat om du varit här förut.",
      "Alve går in som om kroppen minns vägen. Han flyttar en stol, kliver över en låda och tittar mot ett tomt hörn.",
      "Barnet: Du hittar rätt bra här.",
      "Alve: Jag har varit här typ en miljard gånger. Eller… var.",
      "Barnet: När då?",
      "Alve: Varje sommar nästan. Vi kom hit tidigt och åkte hem sent. Ibland sov vi här hur länge som helst.",
      "Barnet: Så du kan hela huset utantill?",
      "Alve: Nästan. Soffan stod där.",
      "Barnet: Det finns ingen soffa.",
      "Alve: Nej, men det gjorde. Bordet stod där. Och där brukade vi lägga handdukar.",
      "Barnet: Varför?",
      "Alve: För att vi kom direkt från sjön.",
      "Barnet: Och vuxna tyckte det var en bra idé?",
      "Alve: Absolut inte.",
      "Barnet: Gjorde ni det ändå?",
      "Alve: Varje gång.",
      "Ni börjar bära ut gamla saker och öppna fönstren.",
      "Barnet: Det här är mer jobb än jag trodde.",
      "Alve: Det ser värre ut än det är.",
      "Barnet: Det där låter som något man säger precis innan man hittar ännu mer jobb.",
      "Alve: Eller precis innan allt går jättebra.",
      "Barnet: Vilket tror du på?",
      "Alve: Det andra. Kom igen. Vi börjar här.",
    ],
    "stage": 1
  },
  {
    "id": "cabin:02",
    "title": "2/16 · Märkena på väggen",
    "image": "/assets/village/story-moments/act2/cabin/1.png",
    "body": [
      "När ni flyttar undan en gammal möbel syns flera bleka streck och små namn på dörrkarmen.",
      "Barnet: Vänta.",
      "Alve: Vad?",
      "Barnet: Det är något på väggen.",
      "Alve: De är kvar.",
      "Barnet: Vad är det?",
      "Alve: Märkena. Den där är jag.",
      "Barnet: Du var jätteliten.",
      "Alve: Jag var jätteliten.",
      "Barnet: Du är fortfarande ganska liten.",
      "Alve: Tyst.",
      "Du följer strecken uppåt.",
      "Barnet: Är alla dina?",
      "Alve: Nej. Några är mina. Några är familjens.",
      "Barnet: Gjorde ni nya varje sommar?",
      "Alve: När någon kom ihåg. Den där sommaren trodde jag att jag hade blivit jättelång.",
      "Barnet: Hade du det?",
      "Alve: Tre centimeter.",
      "Barnet: Imponerande.",
      "Alve: Jag var väldigt stolt.",
      "Barnet: Så hela familjen finns typ kvar här.",
      "Alve: Lite.",
      "Alve stryker försiktigt med fingret över ett av märkena.",
      "Alve: Vi målar inte över dem.",
      "Barnet: Nej.",
      "Alve: Inte ens om resten av väggen ser konstig ut.",
      "Barnet: Då får den vara konstig.",
      "Alve: Bra.",
      "Barnet: Vi kan fixa runtomkring.",
      "Alve: Exakt. De får vara kvar.",
    ],
    "stage": 1
  },
  {
    "id": "cabin:03",
    "title": "3/16 · Fotot",
    "image": "/assets/village/story-moments/act2/cabin/1.png",
    "body": [
      "När ni fortsätter röja lossnar en gammal kartong från väggen. Bakom den ligger ett blekt fotografi.",
      "Barnet: Jag hittade något.",
      "Alve: Om det är en spindel så är den din.",
      "Barnet: Det är ett foto.",
      "Alve: Får jag se?",
      "Barnet: Är det din familj?",
      "Alve: Mm.",
      "Barnet: Är det här nere vid sjön?",
      "Alve: Ja. Där borta vid vattnet.",
      "Barnet: Och det där är du?",
      "Alve: Japp.",
      "Barnet: Du hade väldigt konstiga badbyxor.",
      "Alve: Det där var inte mitt beslut.",
      "Barnet: Säkert.",
      "Alve: Jag var ett barn. Jag hade ingen kontroll.",
      "Barnet: Du är ett barn nu också.",
      "Alve: Nu har jag bättre badbyxor.",
      "Du tittar på fotot igen.",
      "Barnet: Ni ser glada ut.",
      "Alve: Vi var här hela tiden då.",
      "Barnet: Varje sommar?",
      "Alve: Nästan.",
      "Barnet: Vad gjorde ni?",
      "Alve: Badade. Åt frukost ute. Grillade. Spelade kort. Någon brukade alltid bränna korven.",
      "Barnet: Vem?",
      "Alve: Jag tänker inte skvallra.",
      "Barnet: Det var du.",
      "Alve: Jag fick inte ens grilla.",
      "Barnet: Det låter rätt bra.",
      "Alve: Det var det.",
      "Barnet: Vad hände sen?",
      "Alve tittar på fotot lite längre.",
      "Alve: Mamma blev sjuk.",
      "Barnet: Jaha.",
      "Alve: Efter det kom vi nästan aldrig hit.",
      "Barnet: Varför inte?",
      "Alve: Jag vet inte riktigt. Pappa ville inte.",
      "Barnet: Och du?",
      "Alve: Jag ville.",
      "Du låter bilden vila i handen en stund.",
      "Barnet: Vi kan sätta upp fotot igen.",
      "Alve: Här?",
      "Barnet: Ja. När vi har fixat väggen.",
      "Alve: Så man kan se det?",
      "Barnet: Precis.",
      "Alve: Bra.",
      "Barnet: Bredvid märkena kanske.",
      "Alve: Ja."
    ],
    "stage": 1
  },
  {
    "id": "cabin:04",
    "title": "4/16 · Som förr",
    "image": "/assets/village/story-moments/act2/cabin/2.png",
    "body": [
      "Ni har fått undan mycket av skräpet. För första gången går det att se hur stugan faktiskt skulle kunna bli igen.",
      "Barnet: Det börjar ju faktiskt se bra ut.",
      "Alve tittar runt, men ser inte riktigt nöjd ut.",
      "Alve: Inte tillräckligt.",
      "Barnet: Inte tillräckligt för vad?",
      "Alve svarar inte direkt.",
      "Barnet: Alve?",
      "Alve: Jag tänkte att om det såg ut som förr… …så kanske de skulle vilja komma hit igen.",
      "Barnet: Din familj?",
      "Alve: Mm.",
      "Barnet: Är det därför du försökte fixa allt själv?",
      "Alve: Jag tänkte att det kanske skulle gå.",
      "Barnet: Allt det här?",
      "Alve: Jag hade inte riktigt tittat på allt samtidigt.",
      "Barnet: Det var kanske smart.",
      "Alve: Det var väldigt smart tills du kom och började peka på saker.",
      "Du ler lite.",
      "Barnet: Tror du det räcker om det blir som förr?",
      "Alve tittar runt igen.",
      "Alve: Jag vet inte.",
      "Barnet: Men du hoppas.",
      "Alve: Ja. Det var bra här då.",
      "Barnet: Då gör vi det bra här igen.",
      "Alve: Som förr?",
      "Du tittar på märkena, fotot och allt ni redan hunnit fixa.",
      "Barnet: Kanske. Eller bra på något annat sätt.",
      "Alve funderar på det.",
      "Alve: Vi kan börja med att få dörren att gå att stänga.",
      "Barnet: Det känns rimligt."
    ],
    "stage": 2
  },
  {
    "id": "cabin:05",
    "title": "5/16 · Det gamla spelet",
    "image": "/assets/village/story-moments/act2/cabin/renovating-cabin2.png",
    "body": [
      "När ni går igenom ett skåp hittar Alve en sliten låda längst in.",
      "Alve: Nej.",
      "Barnet: Vad?",
      "Alve drar fram lådan.",
      "Alve: Den här finns kvar.",
      "Barnet: Vad är det?",
      "Alve: Ett spel.",
      "Barnet: Det ser väldigt gammalt ut.",
      "Alve: Tack.",
      "Barnet: Jag menade spelet.",
      "Alve: Bra.",
      "Han öppnar lådan. Några delar ligger huller om buller.",
      "Barnet: Är allt med?",
      "Alve: Ingen aning.",
      "Barnet: Bra början.",
      "Alve: Vi spelade det här hela tiden när det regnade.",
      "Barnet: Var det kul?",
      "Alve: Ibland.",
      "Barnet: Det låter inte så övertygande.",
      "Alve: Det blev mest bråk.",
      "Barnet: Om spelet?",
      "Alve: Om reglerna.",
      "Barnet: Vilka regler?",
      "Alve: Exakt.",
      "Du tittar misstänksamt på honom.",
      "Barnet: Du hittade på regler.",
      "Alve: Nej.",
      "Barnet: Du ser ut som någon som hittar på regler när du håller på att förlora.",
      "Alve: Det där är en väldigt allvarlig anklagelse.",
      "Barnet: Är den fel?",
      "Alve börjar lägga tillbaka delarna i lådan.",
      "Alve: Det viktiga är att spelet fortfarande finns.",
      "Barnet: Det där var inte ett svar.",
      "Alve: Det var ett mycket bättre ämne.",
      "Barnet: Ska vi behålla det?",
      "Alve: Ja.",
      "Barnet: Även om delar saknas?",
      "Alve: Vi kan fixa det.",
      "Barnet: Du säger det om väldigt många saker.",
      "Alve: Och nu är vi två."
    ],
    "stage": 2
  },
  {
    "id": "cabin:06",
    "title": "6/16 · Golvet är lava",
    "image": "/assets/village/story-moments/act2/cabin/renovating-cabin2.png",
    "body": [
      "När ni fortsätter flytta möbler börjar Alve plötsligt undvika en del av golvet.",
      "Barnet: Vad gör du?",
      "Alve: Inget.",
      "Alve kliver från en stol till en gammal låda.",
      "Barnet: Du går inte på golvet.",
      "Alve: Jag går på vissa delar av golvet.",
      "Barnet: Varför?",
      "Alve: För att de andra är lava.",
      "Barnet: Är du seriös?",
      "Alve: Extremt.",
      "Barnet: Vi håller på att renovera en stuga.",
      "Alve: Ja.",
      "Barnet: Och nu är golvet lava.",
      "Alve: Det brukade vara det.",
      "Barnet: Hur visste man vilka delar som var lava?",
      "Alve: Man bara visste.",
      "Barnet: Det låter väldigt rättvist.",
      "Alve: Det var det inte.",
      "Alve tar sig över till andra sidan.",
      "Barnet: Lekte ni så här när du var liten?",
      "Alve: Japp. Från soffan till stolen, sen till mattan och upp på trappsteget.",
      "Barnet: Och om man trampade fel?",
      "Alve: Då dog man.",
      "Barnet: Hårt.",
      "Alve: Man fick börja om efter ungefär fem sekunder.",
      "Barnet: Mindre hårt.",
      "Alve tittar tillbaka på dig.",
      "Alve: Kommer du eller?",
      "Barnet: Jag tänker använda golvet.",
      "Alve: Fegt.",
      "Du tar ett steg mot honom och stannar.",
      "Barnet: Vilken del var säker?",
      "Alve ler.",
      "Alve: Jag visste det.",
      "Du kliver upp på en låda.",
      "Barnet: Om jag ramlar är det ditt fel.",
      "Alve: Om du ramlar i lava har vi större problem.",
      "Ni tar er genom rummet mellan möbler och lådor.",
      "Barnet: Det här var faktiskt ganska kul.",
      "Alve: Jag vet.",
      "Barnet: Säg inget.",
      "Alve: För sent."
    ],
    "stage": 2
  },
  {
    "id": "cabin:07",
    "title": "7/16 · Regnet",
    "image": "/assets/village/story-moments/act2/cabin/3.png",
    "body": [
      "Ni har hunnit jobba en stund när regnet börjar slå mot rutorna. Först försiktigt, sedan ordentligt.",
      "Barnet: Det där låter inte som ett litet regn.",
      "Alve: Nej.",
      "Alve tittar ut genom fönstret.",
      "Alve: Vi kommer ingenstans på ett tag.",
      "Barnet: Vi kan fortsätta här inne.",
      "Alve: Vi har flyttat nästan allt som går att flytta utan att något rasar.",
      "Barnet: Så vad gör man i en stuga när det regnar?",
      "Alve tittar mot det gamla spelet.",
      "Alve: Jag har en idé.",
      "Barnet: Det där brukar vara farliga ord.",
      "Alve: Inte den här gången.",
      "Barnet: Det sa du säkert när du hittade på reglerna också.",
      "Alve: Jag hittade inte på regler.",
      "Ni sätter er på golvet med spelet mellan er. Valpen kryper ihop bredvid. Efter en stund flyttar Alve en pjäs.",
      "Barnet: Du fuskar.",
      "Alve: Nej.",
      "Barnet: Du flyttade den där.",
      "Alve: Det gjorde vinden.",
      "Du tittar mot de stängda fönstren.",
      "Barnet: Vi är inomhus.",
      "Alve: Jättekonstig vind.",
      "Barnet: Flytta tillbaka den.",
      "Alve: Då förstör du naturens gång.",
      "Barnet: Alve.",
      "Alve: Okej då.",
      "Ni fortsätter spela. Efter en stund blir Alve tyst och lyssnar.",
      "Barnet: Vad?",
      "Alve: Inget.",
      "Barnet: Du slutade fuska. Något är fel.",
      "Alve: Jag fuskar fortfarande inte. Det låter likadant.",
      "Barnet: Vadå?",
      "Alve: Regnet.",
      "Barnet: Som när ni brukade vara här?",
      "Alve: Mm.",
      "Barnet: Var ni också fast inne då?",
      "Alve: Hela tiden.",
      "Barnet: Och då spelade ni det här?",
      "Alve: Ja.",
      "Barnet: Och fuskade?",
      "Alve: Vi har redan pratat om det här.",
      "Du ler. Regnet fortsätter mot rutorna."
    ],
    "stage": 2
  },
  {
    "id": "cabin:08",
    "title": "8/16 · Det ser bättre ut",
    "image": "/assets/village/story-moments/act2/cabin/3.png",
    "body": [
      "Regnet har slutat. Ni står mitt i rummet och tittar på hur mycket som redan förändrats. Spelet ligger kvar framme.",
      "Barnet: Det känns annorlunda här nu.",
      "Alve: Ja.",
      "Barnet: För att vi har fixat mer?",
      "Alve tittar runt.",
      "Alve: Inte bara.",
      "Barnet: Vad då?",
      "Alve: Jag vet inte. När vi började tänkte jag mest på hur det såg ut förut.",
      "Barnet: Och nu?",
      "Alve: Nu tänker jag på idag också.",
      "Du tittar mot spelet.",
      "Barnet: När du fuskade?",
      "Alve: När vinden flyttade min pjäs.",
      "Barnet: Just det.",
      "Ni börjar ställa tillbaka några saker på sina platser.",
      "Barnet: Ser det ut som förr nu?",
      "Alve stannar upp och tittar runt ordentligt.",
      "Alve: Nej.",
      "Du väntar. Alve ler lite.",
      "Alve: Det ser bättre ut.",
      "Barnet: Bättre än förr?",
      "Alve: Annorlunda bättre.",
      "Barnet: Det låter väldigt praktiskt.",
      "Alve: Det är en riktig sorts bättre.",
      "Barnet: Bra.",
      "Alve flyttar försiktigt spelet till en hylla där det får stå kvar.",
      "Alve: Vi ställer det här.",
      "Barnet: Så vi hittar det nästa gång det regnar?",
      "Alve: Precis.",
      "Barnet: Och nästa gång spelar vi med riktiga regler.",
      "Alve: Vi får se."
    ],
    "stage": 3
  },
  {
    "id": "cabin:09",
    "title": "9/16 · VÅR STUGA",
    "image": "/assets/village/story-moments/act2/cabin/4.png",
    "body": [
      "När ni går igenom en gammal låda hittar Barnet ett vikt papper längst ner.",
      "Barnet: Vad är det här?",
      "Alve: Ingen aning.",
      "Du vecklar försiktigt ut pappret. Det är en gammal barnteckning av stugan, sjön, familjen och en alldeles för stor båt. Överst står det med stora bokstäver: VÅR STUGA.",
      "Barnet: Den här är fantastisk.",
      "Alve: Nej.",
      "Barnet: Jo.",
      "Alve: Lägg tillbaka den.",
      "Barnet: Är det där du?",
      "Alve: Nej.",
      "Du pekar.",
      "Barnet: Det står Alve bredvid.",
      "Alve: …någon annan Alve.",
      "Barnet: Som också bodde här?",
      "Alve: Tydligen.",
      "Barnet: Och hade exakt din familj?",
      "Alve: Väldigt vanligt namn.",
      "Du studerar bilden.",
      "Barnet: Varför är båten nästan lika stor som stugan?",
      "Alve: Perspektiv.",
      "Barnet: Den ligger på gräset.",
      "Alve: Konst behöver inte förklara sig.",
      "Du pekar på figurerna framför huset.",
      "Barnet: Är ni här ute?",
      "Alve tittar.",
      "Alve: På verandan.",
      "Barnet: Den ser större ut på bilden.",
      "Alve: Jag ritade den så som den borde vara.",
      "Barnet: Smart.",
      "Alve tar teckningen och granskar den längre.",
      "Alve: Vi brukade äta frukost där.",
      "Barnet: På verandan?",
      "Alve: Mm. Och fika. Och ibland middag.",
      "Barnet: Ni gjorde mycket ätande.",
      "Alve: Det var en viktig del av semestern.",
      "Du tittar på teckningen igen.",
      "Barnet: Vem sparade den här?",
      "Alve: Mamma.",
      "Barnet: Till och med den här?",
      "Alve: Hon sparade allt.",
      "Barnet: Allt?",
      "Alve: Typ. Särskilt sånt hon trodde att jag skulle skämmas för senare.",
      "Barnet: Smart.",
      "Alve: Nej.",
      "Han pekar på dörren på teckningen.",
      "Alve: Jag sprang alltid ut härifrån ner mot sjön.",
      "Barnet: Med skor?",
      "Alve: Aldrig.",
      "Barnet: Varför inte?",
      "Alve: Det tog för lång tid.",
      "Barnet: Hur lång tid tar det att ta på skor?",
      "Alve: Exakt. För lång tid.",
      "Du tittar från teckningen mot den slitna verandan utanför.",
      "Barnet: Vi borde fixa den.",
      "Alve: Verandan?",
      "Barnet: Ja.",
      "Alve: Som på bilden?",
      "Barnet: Kanske inte exakt.",
      "Du tittar på den gigantiska båten.",
      "Barnet: Jag vet inte om vi har plats.",
      "Alve skrattar.",
      "Alve: Verandan först."
    ],
    "stage": 3
  },
  {
    "id": "cabin:10",
    "title": "10/16 · Verandan",
    "image": "/assets/village/story-moments/act2/cabin/renovating-cabin3.png",
    "body": [
      "Ni börjar plocka undan runt verandan. Teckningen ligger framme som en liten ritning, trots att proportionerna är helt hopplösa.",
      "Barnet: Så här såg den ut?",
      "Alve: Ungefär.",
      "Barnet: På teckningen är den dubbelt så stor.",
      "Alve: Jag ritade efter känsla.",
      "Barnet: Du hade mycket känsla.",
      "Alve: Jag hade stora planer.",
      "Ni börjar flytta bort gammalt bråte och lösa plankor.",
      "Barnet: Vad gjorde ni här ute?",
      "Alve: Åt frukost.",
      "Barnet: Det vet jag.",
      "Alve: Fikade.",
      "Barnet: Det vet jag också.",
      "Alve: Ibland satt vi bara här.",
      "Barnet: Och gjorde vad?",
      "Alve: Inget särskilt.",
      "Du tittar på honom.",
      "Barnet: Det låter ganska tråkigt.",
      "Alve: Nej.",
      "Barnet: Vad gjorde man när man gjorde inget särskilt?",
      "Alve: Pratade. Tittade på sjön. Någon drack kaffe. Någon sa åt mig att inte springa med blöta fötter.",
      "Barnet: Gjorde du det ändå?",
      "Alve: Självklart.",
      "Barnet: Det börjar finnas ett mönster här.",
      "Alve: Jag var konsekvent.",
      "Ni får loss en gammal bräda och hittar mer av verandans ursprungliga kant.",
      "Barnet: Här fortsätter den.",
      "Alve: Jag visste det.",
      "Barnet: Nej, det gjorde du inte.",
      "Alve: Jag hoppades väldigt självsäkert.",
      "Du skrattar.",
      "Barnet: Vi kan göra plats för bord här igen.",
      "Alve: Och stolar.",
      "Barnet: Och frukost.",
      "Alve: Och fika.",
      "Barnet: Du har prioriteringar.",
      "Alve: Bra prioriteringar."
    ],
    "stage": 3
  },
  {
    "id": "cabin:11",
    "title": "11/16 · Vet de om det här?",
    "image": "/assets/village/story-moments/act2/cabin/renovating-cabin3.png",
    "body": [
      "Ni fortsätter arbeta ute på verandan. För första gången börjar den faktiskt kännas som en plats där någon skulle kunna sitta igen.",
      "Barnet: Alve?",
      "Alve: Mm?",
      "Barnet: Vet din familj att du gör det här?",
      "Alve fortsätter med det han håller på med.",
      "Alve: Inte riktigt.",
      "Barnet: Inte riktigt?",
      "Alve: De vet att stugan finns.",
      "Barnet: Det hoppas jag.",
      "Alve: Jag menar att de inte vet att jag håller på och fixar den.",
      "Barnet: Så det är en överraskning?",
      "Alve tvekar.",
      "Alve: Typ.",
      "Barnet: En väldigt stor överraskning.",
      "Alve: Ja.",
      "Barnet: Tänk om de kommer hit innan vi är klara.",
      "Alve stannar upp.",
      "Alve: Det gör de nog inte.",
      "Barnet: Hur vet du det?",
      "Alve: Pappa kommer inte hit längre.",
      "Barnet: Sen din mamma blev sjuk?",
      "Alve: Mm.",
      "Barnet: Varför?",
      "Alve: Jag vet inte riktigt. Jag tror det är svårt för honom.",
      "Barnet: Att vara här?",
      "Alve: Ja.",
      "Du låter det vara en stund.",
      "Barnet: Och när vi är klara?",
      "Alve: Då kanske.",
      "Barnet: Har du tänkt säga till dem?",
      "Alve: Jag vet inte.",
      "Barnet: Hur ska de veta att den är klar annars?",
      "Alve: Jag har inte kommit så långt i planen.",
      "Barnet: Du och dina planer.",
      "Alve: De blir bättre.",
      "Barnet: Gör de?",
      "Alve: Den här har ju dig nu.",
      "Du tystnar lite.",
      "Barnet: Det var faktiskt ett ganska bra svar.",
      "Alve: Jag vet.",
      "Ni fortsätter arbeta."
    ],
    "stage": 3
  },
  {
    "id": "cabin:12",
    "title": "12/16 · Någon har varit här",
    "image": "/assets/village/story-moments/act2/cabin/5.png",
    "body": [
      "När ni kommer tillbaka till stugan nästa gång står något inte riktigt som ni lämnade det.",
      "Barnet: Var den där lådan där förut?",
      "Alve: Nej.",
      "Ni går in. Det är inget stort. Ingen dörr står öppen, inget är förstört. Men något känns annorlunda. Du ser något på golvet.",
      "Barnet: Vad är det?",
      "Alve böjer sig ner och plockar upp en liten nyckelring. Han stannar.",
      "Alve: Den här är inte härifrån.",
      "Barnet: Varifrån är den då?",
      "Alve: Hemma.",
      "Barnet: Hemma hos dig?",
      "Alve: Ja.",
      "Du tittar mot dörren.",
      "Barnet: Så någon har varit här.",
      "Alve säger inget först. Sedan tittar han runt i stugan.",
      "Alve: De har varit här.",
      "Barnet: Det verkar så.",
      "Alve: Då såg de den.",
      "Barnet: Stugan?",
      "Alve: Ja. Och allt vi har gjort.",
      "Barnet: Ja.",
      "Alve tittar ut mot verandan.",
      "Alve: Då måste vi hinna klart.",
      "Barnet: Innan vad?",
      "Alve svarar inte direkt.",
      "Alve: Bara… innan.",
      "Barnet: Tror du de kommer tillbaka?",
      "Alve tittar på nyckelringen.",
      "Alve: Jag vet inte.",
      "Barnet: Men du tror det.",
      "Alve: Jag hoppas.",
      "Han stoppar nyckelringen försiktigt i fickan.",
      "Alve: Kom igen.",
      "Barnet: Nu igen?",
      "Alve: Nu på riktigt.",
      "Barnet: Vad gjorde vi innan?",
      "Alve: Övade."
    ],
    "stage": 4
  },
  {
    "id": "cabin:13",
    "title": "13/16 · Det sista riktiga jobbet",
    "image": "/assets/village/story-moments/act2/cabin/6.png",
    "body": [
      "Ni går igenom stugan en gång till och letar efter det som fortfarande faktiskt behöver lagas.",
      "Barnet: Det börjar bli svårt att hitta trasiga saker.",
      "Alve: Bra.",
      "Barnet: Du låter nästan besviken.",
      "Alve: Jag har blivit väldigt bra på att laga saker.",
      "Barnet: Du kan fortsätta någon annanstans sen.",
      "Alve: Jag tänkte mer att folk kunde börja sluta ha sönder saker.",
      "Du pekar mot en del av väggen.",
      "Barnet: Där då?",
      "Alve: Den räknas knappt.",
      "Barnet: Den är sprucken.",
      "Alve: Lite.",
      "Barnet: Och lös.",
      "Alve: Lite mer.",
      "Barnet: Och du kan se ut genom den.",
      "Alve lutar sig fram och tittar genom springan.",
      "Alve: Fin utsikt.",
      "Barnet: Vi lagar den.",
      "Alve: Ja.",
      "Ni börjar plocka fram det ni behöver.",
      "Alve: Det här kanske är sista riktiga lagningen.",
      "Barnet: Säg inte så.",
      "Alve: Varför?",
      "Barnet: Då hittar vi säkert något jättestort bakom väggen.",
      "Alve stannar.",
      "Alve: Nu gjorde du mig nervös.",
      "Barnet: Bra. Då är vi två.",
      "Ni arbetar vidare tills den sista skadan är borta. Alve känner försiktigt på väggen.",
      "Alve: Stadig.",
      "Barnet: Ordentligt-stadig?",
      "Alve: Har du också börjat med sånt nu?",
      "Barnet: Jag lär mig.",
      "Alve: Ordentligt-stadig."
    ],
    "stage": 4
  },
  {
    "id": "cabin:14",
    "title": "14/16 · Gör plats för människor",
    "image": "/assets/village/story-moments/act2/cabin/6.png",
    "body": [
      "Nu är det inte längre särskilt mycket som behöver repareras. I stället börjar ni ställa i ordning.",
      "Alve: Vad gör vi nu?",
      "Barnet: Gör den redo.",
      "Alve: Den är ju nästan klar.",
      "Barnet: Redo för människor.",
      "Alve tittar runt.",
      "Alve: Det är människor här.",
      "Barnet: Fler människor.",
      "Alve: Jaha.",
      "Ni flyttar ett bord och börjar ställa fram stolar.",
      "Alve: Den där stod nog där förut.",
      "Barnet: Vill du ha den där nu?",
      "Alve tänker efter.",
      "Alve: Nej.",
      "Barnet: Bra.",
      "Alve: Varför?",
      "Barnet: För den stod jättedumt.",
      "Alve: Det gjorde den faktiskt.",
      "Ni flyttar den till ett annat ställe.",
      "Alve: Så här är bättre.",
      "Barnet: Annorlunda bättre?",
      "Alve: Exakt.",
      "Ni fortsätter ordna plats att sitta och sova.",
      "Barnet: Om någon kommer hit nu kan de faktiskt stanna.",
      "Alve saktar ner lite.",
      "Alve: Mm.",
      "Barnet: Vi kan lägga filtar där.",
      "Alve: Och göra plats här.",
      "Han flyttar undan några saker.",
      "Alve: Så man slipper ha väskor mitt på golvet.",
      "Barnet: Du tänker väldigt mycket på var folk ska ha sina saker.",
      "Alve: Man vill ju inte att någon ska komma hit och känna att de är i vägen.",
      "Du tittar på honom.",
      "Barnet: Det kommer de nog inte göra.",
      "Alve nickar och fortsätter.",
      "Alve: Bra."
    ],
    "stage": 4
  },
  {
    "id": "cabin:15",
    "title": "15/16 · Om de kommer",
    "image": "/assets/village/story-moments/act2/cabin/6.png",
    "body": [
      "Stugan är i princip färdig. Ni går runt och tittar på alla små platser som nu går att använda igen. Alve stannar vid sovplatserna.",
      "Alve: De kan sova där.",
      "Barnet: Mm.",
      "Alve går vidare.",
      "Alve: Och vi kan ha spelet här.",
      "Barnet: Med riktiga regler.",
      "Alve: Vi får se.",
      "Han tittar ut genom fönstret.",
      "Alve: Och om det regnar…",
      "Barnet: Då kan vi fuska inomhus.",
      "Alve: Exakt.",
      "Du tittar runt.",
      "Barnet: Du har tänkt ganska mycket på det här.",
      "Alve: Lite.",
      "Barnet: Lite?",
      "Alve: Okej. Ganska mycket.",
      "Han går bort till fotot.",
      "Alve: Jag undrar vad de skulle säga.",
      "Barnet: Om stugan?",
      "Alve: Om allt.",
      "Barnet: De skulle nog märka att du jobbat mycket.",
      "Alve: Vi.",
      "Barnet: Vadå?",
      "Alve: Att vi jobbat mycket.",
      "Du ler.",
      "Barnet: Ja.",
      "Alve tittar runt igen.",
      "Alve: Tänk om de inte vill komma ändå.",
      "Du svarar inte direkt.",
      "Barnet: Då är stugan fortfarande här.",
      "Alve tittar på honom.",
      "Barnet: Och vi är här.",
      "Paus.",
      "Alve: Ja.",
      "Barnet: Och spelet.",
      "Alve: Spelet är viktigt.",
      "Barnet: Trots reglerna.",
      "Alve: Speciellt reglerna.",
      "Alve tittar runt en sista gång.",
      "Alve: Det känns som att någon skulle kunna komma hit nu.",
      "Barnet: Det gör det."
    ],
    "stage": 4
  },
  {
    "id": "cabin:16",
    "title": "16/16 · Stugan är klar",
    "image": "/assets/village/story-moments/act2/cabin/6.png",
    "body": [
      "Ni står utanför stugan och tittar på den. För första gången finns det inget kvar som måste lagas.",
      "Barnet: Så.",
      "Alve: Så?",
      "Barnet: Nu är den klar.",
      "Alve tittar på stugan en lång stund.",
      "Alve: Ja.",
      "Barnet: Det där lät inte särskilt övertygande.",
      "Alve: Jag försöker bara vänja mig vid det.",
      "Barnet: Vid vad?",
      "Alve: Att det inte finns något mer att fixa.",
      "Du tittar mot verandan.",
      "Barnet: Vi kan alltid hitta något om du blir desperat.",
      "Alve: Nej tack.",
      "Ni går in en sista gång. Märkena finns kvar på väggen. Fotot sitter uppe. Spelet står på sin plats. Teckningen VÅR STUGA finns kvar. Alve går långsamt genom rummet.",
      "Alve: Det ser inte ut som förr.",
      "Barnet: Nej.",
      "Alve: Bra.",
      "Barnet: Bra?",
      "Alve: Det är vårt nu också.",
      "Paus.",
      "Barnet: Tror du de kommer?",
      "Alve tittar mot dörren.",
      "Alve: Inte idag.",
      "Barnet: Hur vet du det?",
      "Alve: Det bara känns så.",
      "Du väntar.",
      "Alve: Men den är klar.",
      "Barnet: Det är den.",
      "Alve ser på fotot igen.",
      "Alve: Jag hoppas de får se den.",
      "Barnet: Det tror jag.",
      "Alve: Du vet inte det.",
      "Barnet: Nej. Men jag hoppas också.",
      "Alve nickar. Sedan tittar han ut mot sjön.",
      "Barnet: Vi kommer ju tillbaka imorgon.",
      "Alve: Ja.",
      "Barnet: Och då?",
      "Alve: Vi har ju en båt att laga.",
      "Barnet: Du har redan börjat tänka på nästa grej?",
      "Alve: Någon måste.",
      "Barnet: Det är tydligen vi.",
      "Alve går mot dörren.",
      "Alve: Bra.",
      "Han tittar tillbaka på stugan en sista gång.",
      "Alve: Då går vi.",
    ],
    "stage": 4
  }
];

export const CABIN_WAITING_REACTION: Act2ProjectStoryBeat = {
  id: "cabin:waiting-reaction",
  title: "Stugan är klar · En stund till",
  image: "/assets/village/story-moments/act2/cabin/6.png",
  body: [
  "Ni sitter utanför den färdiga stugan en stund. Allt är klart nu. Dörren går att stänga, verandan är lagad och inne i stugan står spelet och fotot kvar.",
  "Barnet: Väntar du på dem?",
  "Alve svarar inte direkt.",
  "Alve: Lite.",
  "Barnet: Gör du det varje gång vi kommer hit?",
  "Alve rycker på axlarna.",
  "Alve: Kanske.",
  "Barnet: Tror du att de kommer?",
  "Alve tittar ner.",
  "Alve: Jag vet inte.",
  "Barnet: Inte alls?",
  "Alve: Ibland tror jag det.",
  "Barnet: Och ibland?",
  "Alve tittar mot stugan.",
  "Alve: Ibland tänker jag att om de ville komma så hade de redan gjort det.",
  "Du blir tyst en stund.",
  "Barnet: Men någon var ju här.",
  "Alve: Ja.",
  "Barnet: Nyckelringen.",
  "Alve: Jag vet.",
  "Barnet: Så de vet hur det ser ut nu.",
  "Alve: Ja.",
  "Paus.",
  "Barnet: Tror du att din familj någonsin kommer tillbaka?",
  "Alve funderar länge innan han svarar.",
  "Alve: Jag hoppas det.",
  "Barnet: Det var inte riktigt det jag frågade.",
  "Alve: Jag vet.",
  "Du väntar.",
  "Alve: Jag vet faktiskt inte. Jag tror det är svårare för pappa att komma hit än för mig.",
  "Barnet: För att det påminner om förr?",
  "Alve: Kanske.",
  "Alve ser mot verandan.",
  "Alve: När jag började laga stugan tänkte jag att om jag bara gjorde den fin igen så skulle allt bli som förut.",
  "Barnet: Men det blev inte så.",
  "Alve: Nej.",
  "Barnet: Är du ledsen för det?",
  "Alve tänker efter.",
  "Alve: Lite.",
  "Sedan tittar han på dig.",
  "Alve: Men inte lika mycket som jag trodde.",
  "Barnet: Varför inte?",
  "Alve: För att det inte känns tomt här längre.",
  "Du tittar mot stugan.",
  "Barnet: Fast de inte är här?",
  "Alve: Du är ju här.",
  "Paus.",
  "Barnet: Ja.",
  "Alve: Och Valpen.",
  "Barnet: Han räknas väldigt mycket.",
  "Alve: Och vi har saker kvar att göra.",
  "Barnet: Båten.",
  "Alve nickar.",
  "Alve: Båten.",
  "Du reser dig.",
  "Barnet: Då väntar vi inte hela dagen.",
  "Alve ler lite.",
  "Alve: Nej.",
  "Han kastar en sista blick mot vägen.",
  "Alve: Men kanske lite till.",],
  stage: 4,
};
