export type Act2FinaleBeat = {
  id: string;
  title: string;
  image?: string;
  body: string[];
};

export const ACT2_FINALE_BEATS: Act2FinaleBeat[] = [
  {
    "id": "finale:after-motorboat",
    "title": "Efter motorbåten",
    "body": [
      "Motorbåten är klar. För första gången finns det inget stort projekt kvar vid sjön.",
      "Du och Alve står nere vid vattnet och tittar på båten.",
      "Alve: Den fungerar.",
      "Barnet: Japp.",
      "Alve: På riktigt.",
      "Barnet: På riktigt.",
      "Alve lägger handen på relingen.",
      "Alve: Det är lite konstigt.",
      "Barnet: Vadå?",
      "Alve: När jag kom hit var allt trasigt.",
      "Han tittar bort mot stugan, bryggan och båthuset.",
      "Alve: Nu är inget trasigt längre.",
      "Barnet: Vi kan säkert hitta något.",
      "Alve: Nej.",
      "Barnet: Du brukar gilla projekt.",
      "Alve: Jag har fått nog av projekt för typ fem minuter.",
      "Du ler.",
      "Barnet: Vad gör vi då?",
      "Alve tittar ut över sjön.",
      "Alve: Vi skulle kunna åka.",
      "Barnet: Vart?",
      "Alve: Vet inte.",
      "Barnet: Bra plan.",
      "Alve: Jag har blivit bättre på planer.",
      "Barnet: Har du?",
      "Alve: Lite.",
      "Ni börjar gå tillbaka mot stugan."
    ]
  },
  {
    "id": "finale:someone-there",
    "title": "Någon är där",
    "image": "/assets/village/story-moments/act2/finale/01-something-is-different.png",
    "body": [
      "När ni kommer närmare stugan stannar Alve plötsligt.",
      "Alve: Vänta.",
      "Barnet: Vad?",
      "Alve: Dörren.",
      "Du tittar.",
      "Barnet: Vad är det med den?",
      "Alve: Den är öppen.",
      "Barnet: Glömde vi stänga?",
      "Alve: Nej.",
      "Alve går några steg närmare.",
      "Alve: Jag stänger alltid.",
      "Barnet: Alltid?",
      "Alve: Nu gör jag det.",
      "Ni hör ett ljud inifrån. Alve stelnar till.",
      "Alve: Det är någon där.",
      "Barnet: Ja.",
      "Alve: Det kan vara inbrottstjuvar.",
      "Barnet: I en stuga mitt ute vid sjön?",
      "Alve: Perfekt ställe för inbrottstjuvar.",
      "Barnet: Vad skulle de stjäla?",
      "Alve tänker.",
      "Alve: Spelet.",
      "Barnet: Ingen bryter sig in för att stjäla ditt gamla spel.",
      "Alve: Du vet inte hur bra det är.",
      "Ett nytt ljud hörs därinne.",
      "Alve: Okej.",
      "Barnet: Vad gör vi?",
      "Alve: Vi smyger fram.",
      "Barnet: Varför?",
      "Alve: Så de inte märker oss.",
      "Barnet: Och sen?",
      "Alve: Det kommer i nästa del av planen.",
      "Barnet: Du har fortfarande inte blivit bättre på planer.",
      "Alve: Tyst.",
      "Ni går försiktigt fram mot dörren."
    ]
  },
  {
    "id": "finale:family-return",
    "title": "De kom",
    "image": "/assets/village/story-moments/act2/finale/02-family-return.png",
    "body": [
      "Alve öppnar dörren försiktigt.",
      "Han stannar.",
      "Inne i stugan håller hans pappa på att ställa ner en väska. Alves storasyster, i tidiga tonåren, står bredvid en flyttlåda med några saker hemifrån i famnen.",
      "Alve säger ingenting.",
      "Barnet: Alve?",
      "Pappan vänder sig om.",
      "Pappan: Alve?",
      "Alve tar ett steg fram.",
      "Alve: Vad gör ni här?",
      "Det kommer ut lite för snabbt.",
      "Pappan: Vi tänkte att det var dags.",
      "Alve tittar runt. Fler väskor. Några saker hemifrån. Den gamla nyckelringen ligger på ett bord.",
      "Alve: Ni kom.",
      "Pappan: Ja.",
      "Alve står fortfarande helt still.",
      "Pappan tittar runt i den lagade stugan.",
      "Pappan: Jag har åkt hitåt flera gånger.",
      "Alve: Hitåt?",
      "Pappan: Jag kom inte hela vägen.",
      "Alve tittar på honom.",
      "Alve: Varför inte?",
      "Pappan blir tyst ett ögonblick och ser mot rummet omkring sig.",
      "Pappan: Det var svårt att vara här.",
      "Alve svarar inte.",
      "Pappan: Men den här gången kändes det annorlunda.",
      "Han tittar på Alve, sedan på dig.",
      "Pappan: Du har gjort allt det här?",
      "Alve tittar mot dig.",
      "Alve: Vi gjorde det.",
      "Du ler.",
      "Pappan: Det är fantastiskt.",
      "Alve: Det var ganska mycket jobb.",
      "Barnet: Ganska?",
      "Alve: Okej. Väldigt mycket jobb.",
      "Storasystern upptäcker märkena på väggen.",
      "Storasystern: De är kvar.",
      "Alve tittar dit.",
      "Alve: Klart de är.",
      "Pappan ser familjefotot och stannar upp lite längre än vid de andra sakerna.",
      "Pappan: Du satte upp den igen.",
      "Alve: Ja.",
      "Pappan nickar.",
      "Pappan: Bra.",
      "Storasystern får syn på det gamla spelet på bordet och lyfter kartongen.",
      "Storasystern: Den här finns kvar också.",
      "Alve: Ingen får ändra reglerna.",
      "Storasystern: Du menar dina regler?",
      "Alve: Det finns bara regler.",
      "Du börjar skratta.",
      "Barnet: Nu vet vi var han fått det ifrån.",
      "Alve: Va?",
      "Ingen svarar direkt.",
      "Alve tittar runt i rummet igen. Sedan på sin familj.",
      "Alve: Ska ni stanna?",
      "Pappan svarar direkt.",
      "Pappan: Ja.",
      "Alve blinkar.",
      "Alve: Hur länge?",
      "Pappan: Vi tänkte börja med sommaren.",
      "Alve försöker säga något, men får inte riktigt fram det.",
      "Barnet: Du kan säga det.",
      "Alve: Vadå?",
      "Barnet: Att du är glad.",
      "Alve: Jag är jätteglad.",
      "Paus.",
      "Alve: Jag försöker bara att inte vara konstig.",
      "Barnet: Det går sådär."
    ]
  },
  {
    "id": "finale:family-embrace",
    "title": "Min kompis",
    "image": "/assets/village/story-moments/act2/finale/03-family-embrace.png",
    "body": [
      "Alve skrattar till. Storasystern går fram först och kastar armarna om honom. Pappan följer efter och drar in dem båda. Alve försvinner nästan in i familjekramen.",
      "Låt återföreningen landa visuellt innan nästa replik.",
      "Storasystern tittar förbi Alve mot Barnet.",
      "Storasystern: Och vem är det där?",
      "Alve tittar tillbaka.",
      "Alve: Det är {childName}.",
      "Alve: Han är min kompis."
    ]
  },
  {
    "id": "finale:veranda",
    "title": "Det är bättre",
    "image": "/assets/village/story-moments/act2/finale/04-home-again.png",
    "body": [
      "En stund senare har väskorna börjat hitta sina platser. Dörren står öppen bakom er och pappan och storasystern rör sig inne i stugan som om de försiktigt lär känna den igen.",
      "Du och Alve sitter på verandan. För en gångs skull verkar Alve inte ha bråttom någonstans.",
      "Alve: Jag trodde att om jag lagade stugan så skulle allt bli som förr.",
      "Barnet: Blev det det?",
      "Alve tittar in genom den öppna dörren.",
      "Alve: Nej.",
      "Paus.",
      "Alve: Jag kunde inte laga det som hände.",
      "Alve: Men jag kunde laga stugan.",
      "Du tittar på honom.",
      "Barnet: Du lagade mer än stugan.",
      "Alve säger inget först. Han ser på pappan och storasystern därinne, på fotot som sitter kvar och på det gamla spelet som står framme igen.",
      "Alve: Kanske.",
      "Han lutar sig tillbaka.",
      "Alve: Det är inte riktigt som förr.",
      "Barnet: Nej.",
      "Alve ler lite.",
      "Alve: Det är bättre."
    ]
  },
];
