import type { Act2ProjectStoryBeat } from "./act2CabinStory";

export const BOATHOUSE_CONTRIBUTION_BEATS: Act2ProjectStoryBeat[] = [
  {
    "id": "boathouse:01",
    "title": "1/16 · Under bråten",
    "image": "/assets/village/story-moments/act2/boathouse/under-the-rubble.png",
    "body": [
      "Ni börjar röja det gamla båthuset. Det luktar trä, sjö och gammalt damm. Överallt ligger trasiga plankor, lådor och rep.",
      "Alve står mitt i röran och ser nästan nöjd ut.",
      "Barnet: Du ser väldigt glad ut för någon som står mitt i ett jättestök.",
      "Alve: Det är bra stök. Man vet aldrig vad som finns under.",
      "Du lyfter undan en gammal låda.",
      "Barnet: Jag hoppas på något som inte har åtta ben.",
      "Alve: Jag hoppas på verktyg. Eller en hemlig lucka. Jag vet att det inte borde finnas en här, men båthuset hade varit bättre om det gjorde det.",
      "Ni fortsätter röja. En stor hög med gammalt bråte längst in sitter ovanligt hårt, och Alve får knappt loss en planka.",
      "Alve: Det är något under.",
      "Barnet: Hur vet du det?",
      "Alve: För att allt annat flyttar på sig och det här vägrar.",
      "Ni börjar försiktigt ta bort saker ovanifrån. Efter en stund syns kanten på något mörkt och tungt.",
      "Barnet: Det där är inte golvet. Det är en väldigt stor låda.",
      "Alve: Ännu bättre. Stora lådor innehåller bättre saker än små lådor.",
      "Barnet: Det där har du hittat på.",
      "Alve: Det känns sant.",
      "Ni får undan tillräckligt mycket för att se att det är en gammal tung kista.",
      "Alve tittar på den med ett stort leende.",
      "Alve: Okej. Nu blev det här projektet mycket bättre.",
      "Barnet: Vi skulle laga båthuset.",
      "Alve: Det gör vi. Fast först tar vi reda på vad det där är.",
    ],
    "stage": 1
  },
  {
    "id": "boathouse:02",
    "title": "2/16 · Den låsta kistan",
    "image": "/assets/village/story-moments/act2/boathouse/finding-chest.png",
    "body": [
      "Ni har fått fram hela kistan. Den är tung, smutsig och låset ser ut att ha suttit där ungefär lika länge som båthuset.",
      "Alve drar i locket. Det rör sig inte. Han drar hårdare. Fortfarande ingenting.",
      "Barnet: Jag tror den är låst.",
      "Alve släpper taget och tittar på dig.",
      "Alve: Jag märkte det.",
      "Barnet: Ville bara hjälpa.",
      "Alve börjar undersöka låset.",
      "Alve: Det här borde gå. Jag behöver bara komma på med vad.",
      "Du tittar runt på alla gamla saker omkring er.",
      "Barnet: Bra plan.",
      "Alve provar först försiktigt och sedan lite mindre försiktigt. Till slut sätter han sig bredvid kistan.",
      "Alve: Den hatar mig.",
      "Barnet: Det är ett lås.",
      "Alve: Det är personligt nu.",
      "Ni provar flera rimliga sätt att få upp den, men låset sitter fast.",
      "Efter en stund lutar du dig mot väggen.",
      "Barnet: Vi kanske behöver hjälp.",
      "Alve tittar fortfarande på kistan.",
      "Alve: Jag vill inte ge upp mot en låda.",
      "Barnet: Vi ger inte upp. Vi hittar bara någon som är bättre på gamla lås.",
      "Alve funderar.",
      "Alve: Linus kanske. Eller Henning.",
      "Barnet: Varför Henning?",
      "Alve: Jag vet inte. Han känns som någon som har idéer.",
      "Du tänker på Henning.",
      "Barnet: Det där är både sant och lite oroande.",
      "Alve reser sig.",
      "Alve: Perfekt. Då frågar vi honom.",
    ],
    "stage": 1
  },
  {
    "id": "boathouse:03",
    "title": "3/16 · Henning har en idé",
    "image": "/assets/village/story-moments/act2/boathouse/henning-will-blow-it-open.png",
    "body": [
      "Henning kommer ner till båthuset och går ett långsamt varv runt kistan. Du och Alve väntar medan han fortsätter granska den.",
      "Alve: Har du någon idé?",
      "Henning nickar långsamt.",
      "Henning: Japp.",
      "Barnet: En normal idé?",
      "Henning: Vad menar du med normal?",
      "Alve tittar på dig.",
      "Alve: Det där var inte ett bra svar.",
      "Henning böjer sig ner och granskar låset.",
      "Henning: Det är gammalt. Rostigt. Och sitter ordentligt.",
      "Alve: Det vet vi.",
      "Henning: Ni har försökt få upp det?",
      "Barnet: Ja. Försiktigt. Mestadels.",
      "Alve hostar lite.",
      "Henning reser sig.",
      "Henning: Då behöver vi något som är mindre försiktigt.",
      "Alve lyser upp.",
      "Alve: Jag gillar redan den här planen.",
      "Du tittar misstänksamt på Henning.",
      "Barnet: Hur mycket mindre försiktigt pratar vi om här?",
      "Henning: Tillräckligt. Jag har dynamit.",
      "Alve vänder sig mot dig med ett ansiktsuttryck som säger att detta är den bästa dagen hittills.",
      "Alve: Han har dynamit. Varför har bagaren dynamit?",
      "Henning: Det är en lång historia.",
      "Barnet: Vi ska inte fråga.",
      "Alve: Jag vill väldigt gärna fråga.",
      "Henning börjar ordna med sin plan.",
      "Vi klipper bort långt innan något praktiskt visas.",
      "Alve lutar sig lite mot dig.",
      "Alve: Är det här normalt här?",
      "Du tittar på Henning.",
      "Sedan tillbaka på Alve.",
      "Barnet: Tyvärr börjar det kännas så.",
    ],
    "stage": 1
  },
  {
    "id": "boathouse:04",
    "title": "4/16 · BOOM",
    "image": "/assets/village/story-moments/act2/boathouse/henning-after-tnt.png",
    "body": [
      "Vi lämnar båthuset. Henning gör det Henning tänker göra, helt utanför bild.",
      "BOOM.",
      "När ni kommer tillbaka står Henning framför båthuset med sot i ansiktet och ett väldigt nöjt uttryck. Kistan är öppen.",
      "Alve stannar.",
      "Alve: Är alla i din by så här?",
      "Du tittar på Henning och sedan på Alve.",
      "Barnet: Typ.",
      "Alve: …jag gillar den här byn.",
      "Henning borstar lite sot från ärmen.",
      "Henning: Det gick ju bra.",
      "Barnet: Det beror lite på hur man räknar.",
      "Henning: Kistan är öppen.",
      "Alve går redan mot den.",
      "Alve: Det är det viktiga.",
      "Ni sätter er bredvid kistan och går igenom innehållet. Där finns gamla verktyg, beslag, repstumpar och delar som ser ut att ha hört till båtar.",
      "Alve plockar upp en metallbit.",
      "Alve: Den här ser viktig ut.",
      "Barnet: Vet du vad det är?",
      "Alve: Nej.",
      "Barnet: Då vet vi att den är viktig.",
      "Längre ner hittar du ett gammalt fotografi.",
      "Du blåser bort dammet.",
      "Bilden visar sjön för många år sedan. Bryggan är hel. Båthuset ser nytt ut. Folk är ute på vattnet.",
      "Och mitt i bilden syns en motorbåt.",
      "Alve lutar sig närmare.",
      "Alve: Den där båten… det är ju den.",
      "Du tittar från bilden mot den gamla båten.",
      "Barnet: Den på bilden?",
      "Alve: Mm.",
      "På baksidan av fotografiet står det:",
      "“Sista turen över sjön innan hösten.”",
      "Alve läser texten en gång till.",
      "Sedan tittar han ut genom båthusets öppning, över sjön.",
      "Alve: Jag undrar vart de brukade åka.",
    ],
    "stage": 2
  },
  {
    "id": "boathouse:05",
    "title": "5/16 · Fynden",
    "image": "/assets/village/story-moments/act2/boathouse/alve-finds-a-tool.png",
    "body": [
      "Nästa gång ni kommer tillbaka ligger allt från kistan utspritt över golvet. Verktyg på ett ställe, båtdelar på ett annat och en hög med saker ni fortfarande inte förstår.",
      "Alve står mitt bland högarna.",
      "Alve: Jag har gjort ett system.",
      "Barnet: Vilket system?",
      "Alve: Saker jag förstår. Saker jag nästan förstår. Och saker som antagligen är väldigt viktiga.",
      "Den sista högen är störst.",
      "Barnet: Du förstår alltså nästan ingenting.",
      "Alve: Jag förstår att vi behöver spara allt.",
      "Du plockar upp fotografiet igen.",
      "Alve märker det direkt.",
      "Alve: Jag har tänkt på den där båten. Den ser inte gammal ut på bilden, och nu står den bara här.",
      "Barnet: Den har nog stått där länge.",
      "Alve går fram till båten och lägger handen på sidan.",
      "Alve: Tänk om några av delarna i kistan hör till den.",
      "Barnet: Då kanske vi kan använda dem senare.",
      "Alve: Senare?",
      "Barnet: Vi håller fortfarande på med båthuset.",
      "Alve ser sig omkring på det trasiga arbetsbordet, verktygen på golvet och bråtet i hörnen. Han suckar.",
      "Alve: Okej. Jag erkänner att det här inte är världens bästa verkstad.",
      "Barnet: Det är knappt en verkstad.",
      "Alve: Än.",
      "Han plockar upp fotografiet och sätter det försiktigt mot väggen.",
      "Alve: Men den där stannar här.",
    ],
    "stage": 2
  },
  {
    "id": "boathouse:06",
    "title": "6/16 · Mira ser problemet",
    "image": "/assets/village/story-moments/act2/boathouse/mira-you-need-more-tools.png",
    "body": [
      "Mira kommer ner till båthuset och stannar i dörröppningen. Hon tittar på golvet, arbetsbordet och Alves tre högar.",
      "Mira: Vad har hänt här?",
      "Alve: Vi organiserar.",
      "Barnet: Han organiserar.",
      "Mira: Det förklarar en del.",
      "Hon går fram till verktygen.",
      "Mira: Ni har faktiskt hittat en hel del användbart. Problemet är att allt ligger överallt.",
      "Alve pekar på sina högar.",
      "Alve: Inte överallt. På tre väldigt tydliga ställen.",
      "Mira tittar på den sista högen.",
      "Mira: Ni behöver inte fler verktyg. Ni behöver kunna hitta de ni redan har.",
      "Hon pekar på den gamla arbetsplatsen.",
      "Mira: Fixa arbetsbordet först. Sedan behöver ni någonstans att hänga verktygen, lådor till smådelarna och bättre ljus här inne. Annars kommer ni lägga halva tiden på att leta efter saker.",
      "Alve tittar runt.",
      "Alve: Det låter mindre roligt än att bygga något.",
      "Mira: Det är därför man gör det först.",
      "Du tittar på Alve.",
      "Barnet: Hon låter lite som Linus.",
      "Alve: Alla vuxna verkar dela en hemlig bok.",
      "Mira ler.",
      "Mira: Vi får den när vi fyller arton.",
      "Alve tittar mot motorbåten.",
      "Alve: När verkstaden är klar kan vi börja med den.",
      "Barnet: När de andra projekten är klara.",
      "Alve suckar, men inte särskilt hårt.",
      "Alve: Jag vet. Okej. Då bygger vi en riktig verkstad först.",
    ],
    "stage": 2
  },
  {
    "id": "boathouse:07",
    "title": "7/16 · Verkstaden tar form",
    "image": "/assets/village/story-moments/act2/boathouse/mira-you-need-more-tools.png",
    "body": [
      "Nästa gång ni kommer tillbaka har Mira ordnat det ni behöver. Lådor, förvaring, krokar och bättre belysning ligger samlat vid arbetsbordet.",
      "Alve tittar på allt.",
      "Alve: Det här är väldigt många saker för att kunna hitta andra saker.",
      "Barnet: Det är ungefär hela poängen med förvaring.",
      "Ni sätter igång.",
      "Det gamla arbetsbordet blir stadigt igen. Verktyg får egna platser. Smådelarna från kistan hamnar i lådor istället för i Alves tre högar.",
      "Efter en stund står Alve mitt i rummet och ser sig omkring.",
      "Alve: Jag hatar att erkänna det här, men Mira hade rätt. Det är faktiskt lättare när man inte behöver leta efter hammaren varje gång.",
      "Barnet: Fotot då?",
      "Alve tar försiktigt upp det gamla fotografiet, funderar en stund och hänger det ovanför arbetsbordet.",
      "Alve: Där.",
      "Barnet: Bra plats.",
      "Alve tittar på bilden.",
      "På båten ute på sjön.",
      "Sedan på den gamla motorbåten som står i båthuset.",
      "Alve: Nu känns det nästan som att den väntar på oss.",
      "Barnet: Båten?",
      "Alve: Ja.",
      "Han vänder tillbaka mot arbetsbordet.",
      "Alve: Men först verkstaden.",
      "Du tittar på honom.",
      "Barnet: Du sa det själv.",
      "Alve: Skriv upp datumet.",
    ],
    "stage": 2
  },
  {
    "id": "boathouse:08",
    "title": "8/16 · Vår verkstad",
    "image": "/assets/village/story-moments/act2/boathouse/mira-you-need-more-tools.png",
    "body": [
      "När ni kommer tillbaka är båthuset förändrat. Det är fortfarande gammalt och lite snett här och där, men det fungerar.",
      "Arbetsbordet är helt. Verktygen hänger där de ska. Lådorna är märkta. Fotografiet sitter kvar på väggen.",
      "Alve lägger ifrån sig ett verktyg på rätt plats.",
      "Barnet: Du la tillbaka den. Frivilligt?",
      "Alve: Jag gör det nu. Jag vill inte prata om det.",
      "Ni sätter er en stund på arbetsbänken och tittar ut över sjön.",
      "Barnet: Det blev faktiskt bra.",
      "Alve tittar runt.",
      "Alve: Det känns inte som ett gammalt båthus längre. Det känns som vår verkstad.",
      "Det blir tyst en stund.",
      "Sedan reser han sig igen.",
      "Alve: Vad ska vi bygga? Vi behöver ju något att använda verkstaden till.",
      "Barnet: Vi har precis blivit klara.",
      "Han ser sig omkring bland lådorna, hyllorna och delarna ni sparat.",
      "Barnet: Vad tänker du bygga?",
      "Alve ler.",
      "Alve: Allt.",
      "Sedan tittar han mot den gamla motorbåten.",
      "Alve: Men först ska vi fixa den gamla båten.",
      "Du skakar på huvudet.",
      "Barnet: Inte än.",
      "Alve tittar på dig.",
      "Alve: Jag vet.",
      "Alve: Men jag kan tänka på den.",
    ],
    "stage": 3
  },
  {
    "id": "boathouse:09",
    "title": "9/16 · En gammal ritning",
    "image": "/assets/village/story-moments/act2/boathouse/boxcar-blueprint.png",
    "body": [
      "Ni går igenom det sista som fortfarande ligger kvar i ett hörn av båthuset.",
      "Gamla papper. Några brädor. En burk med skruvar som kanske är äldre än både dig och Alve tillsammans.",
      "Du drar fram en hopvikt pappersbit.",
      "Barnet: Vad är det här?",
      "Ni vecklar ut den på arbetsbordet. Det är en handritad plan med fyra hjul, en enkel ram och ett säte.",
      "Alve lutar sig närmare.",
      "Alve: Det där är en lådbil.",
      "Barnet: Ser ut så.",
      "Alve tittar från ritningen till verkstaden och tillbaka igen. Du känner igen blicken direkt.",
      "Barnet: Nej. Jag vet redan att du tänker säga att vi ska bygga den.",
      "Alve ler stort.",
      "Alve: Bra. Då är vi överens.",
      "Du tittar på ritningen igen.",
      "Den är gammal och lite sliten, men fortfarande tydlig nog.",
      "Barnet: Tror du den här faktiskt har blivit byggd någon gång?",
      "Alve: Kanske. Eller så hann någon aldrig.",
      "Han skjuter ritningen mot mitten av arbetsbordet.",
      "Alve: Då är det väl dags.",
      "Du tittar på verkstaden ni precis gjort klar.",
      "Verktygen.",
      "Delarna.",
      "Allt har plötsligt ett syfte.",
      "Barnet: Okej. Vi bygger en lådbil.",
      "Alve slår händerna mot bordet.",
      "Alve: Äntligen.",
    ],
    "stage": 3
  },
  {
    "id": "boathouse:10",
    "title": "10/16 · Lådbilen byggs",
    "image": "/assets/village/story-moments/act2/boathouse/boxcar-built.png",
    "body": [
      "Ni lägger ritningen mitt på arbetsbordet och börjar bygga. Ratten från Mira ligger bredvid.",
      "Alve håller upp den.",
      "Alve: Det här är definitivt den viktigaste delen.",
      "Barnet: Viktigare än hjulen?",
      "Alve: Man måste kunna känna att man kör något.",
      "Ni återanvänder trä, beslag och delar ni hittat i båthuset.",
      "Arbetet tar längre tid än Alve först tänkt, men den här gången klagar han inte särskilt mycket.",
      "Efter ett tag börjar något faktiskt likna en lådbil. Alve backar några steg.",
      "Alve: Okej. Den ser snabb ut.",
      "Barnet: Den står still.",
      "Alve: Den ser snabbt stillastående ut.",
      "Du testar ratten. Den sitter fast. Alve trycker försiktigt på ett hjul.",
      "Alve: Det där sitter också.",
      "Barnet: Säger du det som ett faktum eller ett hopp?",
      "Alve: Lite av båda.",
      "Ni gör klart de sista detaljerna.",
      "När ni till slut rullar ut lådbilen framför båthuset stannar Alve bredvid den.",
      "Alve: Det här är det första vi byggt här som inte fanns innan.",
      "Du tittar tillbaka mot verkstaden.",
      "Barnet: Inte illa för ett gammalt båthus.",
      "Alve tittar på lådbilen igen.",
      "Alve: Vi borde testa den.",
      "Barnet: Jag visste att du skulle säga det.",
    ],
    "stage": 3
  },
  {
    "id": "boathouse:11",
    "title": "11/16 · Första provturen",
    "image": "/assets/village/story-moments/act2/boathouse/boxcar-broken.png",
    "body": [
      "Ni hittar en kort, lugn sträcka där lådbilen kan testas.",
      "Alve sätter sig bakom ratten.",
      "Barnet: Du behöver inte försöka slå något rekord.",
      "Alve: Jag tänkte mest försöka komma framåt.",
      "Barnet: Bra början.",
      "Alve skjuter ifrån. Lådbilen börjar rulla, först försiktigt och sedan lite snabbare.",
      "Alve: Den funkar!",
      "Du följer efter. Sedan hörs ett ljud. Ett hjul lossnar och rullar åt sidan, och lådbilen stannar snabbt och odramatiskt.",
      "Du kommer fram.",
      "Alve sitter kvar och tittar efter hjulet.",
      "Barnet: Gick det bra? Hjulet lossnade.",
      "Alve: Japp. Då vet vi vad vi ska fixa.",
      "Du börjar skratta.",
      "Alve kliver ur och hämtar hjulet.",
      "Alve håller upp hjulet.",
      "Alve: Det här var ett test som visade exakt vad som behövde bli bättre. Det är nästan mer användbart.",
      "Barnet: Nästan.",
      "Ni tar tillbaka lådbilen till verkstaden.",
      "För första gången ser misslyckandet inte ut att irritera Alve särskilt mycket.",
      "Han lägger hjulet på arbetsbordet.",
      "Alve: Version två.",
    ],
    "stage": 3
  },
  {
    "id": "boathouse:12",
    "title": "12/16 · Version två",
    "image": "/assets/village/story-moments/act2/boathouse/boxcar-working.png",
    "body": [
      "Ni går igenom hela lådbilen tillsammans, inte bara hjulet som lossnade. Den här gången försöker Alve inte skynda.",
      "När du märker det säger du inget först.",
      "Efter en stund tittar han upp.",
      "Alve: Vad? Du gjorde den där blicken.",
      "Barnet: Vilken blick?",
      "Alve: Den där ‘Alve gör något oväntat vettigt’-blicken.",
      "Du ler.",
      "Barnet: Jag tänkte bara att du inte verkar ha bråttom.",
      "Alve fortsätter arbeta.",
      "Alve tittar mot hjulet.",
      "Alve: Det gick ju fort förra gången. Det hjälpte inte så mycket.",
      "Ni gör klart version två.",
      "När den rullas ut ser den nästan likadan ut, men den är bättre byggd.",
      "Alve sätter sig bakom ratten igen.",
      "Alve: Redo?",
      "Barnet: Jag står bredvid. Du är den som ska köra.",
      "Alve: Bra poäng.",
      "Han rullar iväg.",
      "Den här gången håller alla fyra hjulen sig där de ska.",
      "Alve kommer tillbaka med ett stort leende.",
      "Alve: Nu fungerade den på riktigt.",
      "Du går runt bilen och tittar.",
      "Barnet: Och alla hjulen är kvar.",
      "Alve: Överdrivet lyxigt.",
      "Ni rullar tillbaka lådbilen till båthuset och ställer den bredvid arbetsbänken.",
      "Alve ser på den en stund.",
      "Alve: Okej. Den där var övning.",
      "Barnet: För vad?",
      "Alve tittar mot den gamla motorbåten.",
      "Alve: Båten.",
    ],
    "stage": 4
  },
  {
    "id": "boathouse:13",
    "title": "13/16 · Gör plats för båten",
    "image": "/assets/village/story-moments/act2/boathouse/boat-ramp.png",
    "body": [
      "Efter lådbilen står ni kvar i verkstaden och tittar runt. Det har blivit mycket bättre här inne, men längst in ligger fortfarande bråte, plankor och delar i vägen.",
      "Alve följer din blick.",
      "Alve: Okej. Jag ser problemet. Det är ungefär lika brett som en båt.",
      "Barnet: Bra, då pratar vi om samma.",
      "Ni går fram till den gamla båtplatsen.",
      "Alve försöker uppskatta utrymmet.",
      "Alve: Om vi ska laga båten här inne så måste den faktiskt få plats här inne.",
      "Barnet: Bra början.",
      "Alve nickar mot lådbilen.",
      "Alve: Vi kanske måste flytta lådbilen. Det gör lite ont att säga.",
      "Barnet: Du överlever.",
      "Ni börjar röja. Det går snabbare än förr eftersom ni nu vet var saker ska hamna.",
      "Efter ett tag syns den gamla båtplatsen igen. På golvet finns spår efter något tungt som en gång rullats in och ut.",
      "Alve böjer sig ner.",
      "Alve: Vad är det här?",
      "Barnet: Ser ut som att något har gått här. Spåren fortsätter hela vägen mot vattnet.",
      "Alve följer dem med blicken.",
      "Alve: Båten. Det måste ha funnits något som drog in den.",
    ],
    "stage": 4
  },
  {
    "id": "boathouse:14",
    "title": "14/16 · Den gamla slipen",
    "image": "/assets/village/story-moments/act2/boathouse/boat-ramp.png",
    "body": [
      "Linus kommer ner, går längs spåren och stannar vid resterna av den gamla mekanismen.",
      "Linus: Det här är inte bara spår. Här har suttit en slipvagn.",
      "Alve tittar på honom.",
      "Alve: En vadå?",
      "Linus: En slipvagn. Tänk dig en låg vagn som båten står på. Den går på de här spåren så man kan dra båten upp ur vattnet och in i båthuset utan att lyfta hela båten.",
      "Alve följer spåren med blicken.",
      "Alve: Så båten åkte på en liten vagn?",
      "Linus: Ungefär. Vagnen går i vattnet, båten hamnar ovanpå och sedan drar man in allt tillsammans. Betydligt enklare än att bära en båt.",
      "Alve ser genast intresserad ut.",
      "Alve: Kan vi laga den?",
      "Linus undersöker delarna.",
      "Linus: Kanske. Mycket är rostigt, men själva konstruktionen ser ut att gå att rädda.",
      "Ni hämtar fram delarna från kistan igen. Alve jämför dem med mekanismen och håller plötsligt upp en av metallbitarna.",
      "Alve: Den här passar ju.",
      "Linus provar den. Den passar faktiskt.",
      "Barnet: Så den viktiga saken var viktig?",
      "Alve: Jag sa ju det.",
      "Barnet: Du visste inte ens vad den var.",
      "Alve: Detaljer.",
      "Linus fortsätter gå igenom delarna.",
      "Linus: Det här är bra. Några av sakerna ni hittade i kistan hör faktiskt hit.",
      "Alve tittar bort mot det gamla fotografiet på väggen.",
      "Alve: Så de sparade delar till allt.",
      "Linus: Förmodligen. Förr lagade man ofta sådant här istället för att kasta det.",
      "Barnet: Det låter som du.",
      "Linus: Då var de kloka.",
      "Alve ler.",
      "Alve: Där kom det.",
      "Ni börjar återställa mekanismen tillsammans.",
    ],
    "stage": 4
  },
  {
    "id": "boathouse:15",
    "title": "15/16 · Den fungerar",
    "image": "/assets/village/story-moments/act2/boathouse/boat-ramp.png",
    "body": [
      "Den gamla slipvagnen är på plats igen. Inte blank och ny, men hel.",
      "Alve står bredvid den och försöker inte se alltför förväntansfull ut. Det går sådär.",
      "Alve: Vi måste testa den.",
      "Barnet: Ja. Det är nästan som att test är en del av att laga saker.",
      "Alve: Du sa ja väldigt snabbt. Jag känner att du och Linus har pratat för mycket.",
      "Ni testar mekanismen utan motorbåten först. Vagnen rör sig långsamt längs spåret, ut och sedan in igen. Allt håller.",
      "Alve går bredvid och tittar på varje del.",
      "När vagnen stannar på sin plats står han kvar en stund.",
      "Alve: Den fungerar. Då kan vi få in båten.",
      "Barnet: När vi får laga den.",
      "Alve nickar, den här gången utan protest.",
      "Alve: När vi får laga den.",
      "Han ser sig omkring i båthuset. Verkstaden, fotografiet, lådbilen och slipen. Allt är redo.",
      "Alve: Det känns faktiskt som att vi byggt hela platsen för den.",
      "Barnet: Inte bara för den.",
      "Alve tittar på lådbilen.",
      "Sedan på arbetsbordet.",
      "Alve: Nej.",
      "Han ler.",
      "Alve: Men ganska mycket för den.",
    ],
    "stage": 4
  },
  {
    "id": "boathouse:16",
    "title": "16/16 · Båthuset är klart",
    "image": "/assets/village/story-moments/act2/boathouse/16.png",
    "body": [
      "När ni kommer tillbaka till båthuset nästa gång finns det egentligen inget kvar att reparera.",
      "Verkstaden fungerar. Verktygen har sina platser. Fotografiet sitter ovanför arbetsbordet. Lådbilen står vid väggen. Slipvagnen fungerar och båtplatsen är röjd.",
      "Alve står mitt i allt och ser sig omkring.",
      "Barnet: Klart.",
      "Alve tittar runt ett varv till.",
      "Alve: Nästan.",
      "Barnet: Vad är det som är kvar? Båthuset är ju klart.",
      "Alve pekar mot motorbåten.",
      "Alve: Jag vet. Den är kvar.",
      "Han går fram till arbetsbordet och tittar på fotografiet från kistan.",
      "Den gamla bilden visar båten ute på sjön, från en tid när allt här användes.",
      "Alve: När vi hittade den här trodde jag mest att vi hade hittat ännu en gammal grej.",
      "Barnet: Och nu?",
      "Alve: Nu känns det som att allt här hänger ihop. Verktygen, delarna, slipen, båten…",
      "Han tittar på lådbilen och ler.",
      "Alve: Och en väldigt snabb bil.",
      "Barnet: Med fyra hjul.",
      "Alve: Numera.",
      "Han går fram till motorbåten.",
      "Alve: Förut stod den bara här och blev äldre. Nu har vi faktiskt någonstans att laga den.",
      "Barnet: När det är dags.",
      "Alve nickar, den här gången utan att protestera.",
      "Alve: När det är dags.",
      "Han lägger handen mot båten.",
      "Alve: Men då är det vår tur.",
      "Barnet: Vår tur?",
      "Alve tittar från båten till fotografiet och sedan ut över sjön.",
      "Alve: Att ta reda på om den fortfarande kan åka någonstans.",
    ],
    "stage": 4
  }
];

export const BOATHOUSE_STEERING_WHEEL_BEAT: Act2ProjectStoryBeat = {
  id: "boathouse:steering-wheel",
  title: "Mellan 9 och 10 · Ratten till lådbilen",
  image: "/assets/village/story-moments/act2/boathouse/boxcar-blueprint.png",
  body: [
  "Ni har börjat plocka fram delar till lådbilen. Alve lägger ut allt på arbetsbordet.",
  "Alve: Fyra hjul, trä, skruvar, ett säte… vi har nästan allt.",
  "Barnet: Inte allt.",
  "Du pekar på ratten på ritningen. Alve tittar på delarna igen.",
  "Alve: Okej. Vi har ingen ratt. Man kan säkert styra på något annat sätt.",
  "Barnet: Det känns som en ganska viktig del. Vi köper en ratt.",
  "Alve: Du har blivit väldigt tråkigt klok sedan du började umgås med Linus.",
  "Hos Mira lägger hon fram en liten enkel ratt som passar projektet.",
  "Mira: Till en lådbil?",
  "Barnet: Japp.",
  "Mira: Och Alve ska köra den?",
  "Alve: Japp.",
  "Mira skjuter ratten lite närmare dig.",
  "Mira: Tvåhundra SysselBux.",
  "Efter köpet tar Alve upp ratten.",
  "Alve: Nu har vi allt.",
  "Mira: Det där är exakt den sortens mening som brukar göra mig nervös.",
  "Alve: Du kommer ändra dig när du ser den.",
  "Mira: Det är också en mening som gör mig nervös.",
],
  stage: 3,
};
