import type { Act2ProjectStoryBeat } from "./act2CabinStory";

export const MOTORBOAT_CONTRIBUTION_BEATS: Act2ProjectStoryBeat[] = [
  {
    "id": "motorboat:01",
    "title": "1/16 · Äntligen båten",
    "image": "/assets/village/story-moments/act2/motorboat/01-finally-the-boat.png",
    "body": [
      "Ni står i det färdiga båthuset och tittar på motorbåten.",
      "Alve står helt stilla ovanligt länge.",
      "Barnet: Du tänker säga det, eller hur?",
      "Alve: Vadå?",
      "Barnet: Att vi äntligen får börja med båten.",
      "Alve försöker låta lugn.",
      "Alve: Jag tänkte faktiskt inte säga det.",
      "Paus.",
      "Alve: ÄNTLIGEN.",
      "Barnet: Där var det.",
      "Alve går runt båten och tittar på den från alla håll.",
      "Alve: Vi har lagat stugan.",
      "Barnet: Japp.",
      "Alve: Bryggan.",
      "Barnet: Japp.",
      "Alve: Båthuset.",
      "Barnet: Jag ser vart det här är på väg.",
      "Alve lägger handen på båten.",
      "Alve: Nu är det din tur.",
      "Barnet: Pratar du med båten?",
      "Alve: Den har väntat länge.",
      "Barnet: Det har du också.",
      "Alve: Exakt.",
      "Ni börjar dra undan det som legat över båten och göra plats runt den.",
      "Barnet: Den ser ganska ledsen ut.",
      "Alve: Den ser gammal ut.",
      "Barnet: Den kan vara båda.",
      "Alve torkar bort smuts från sidan.",
      "Alve: Jag minns den nästan så här.",
      "Barnet: Trasig?",
      "Alve: Nej.",
      "Han tittar på den en stund.",
      "Alve: Större.",
      "Barnet: Du var mindre.",
      "Alve tittar på dig.",
      "Alve: Det behöver inte vara förklaringen till allt.",
      "Barnet: Det förklarar ganska mycket.",
      "Ni fortsätter röja fram båten.",
      "Alve: Tänk om den faktiskt går att få igång.",
      "Barnet: Det är väl därför vi är här.",
      "Alve: Ja.",
      "Paus.",
      "Alve: Men tänk om den gör det.",
      "Den här gången svarar Barnet inte med ett skämt.",
      "Barnet: Då åker vi.",
      "Alve ler.",
      "Alve: Då åker vi."
    ],
    "stage": 1
  },
  {
    "id": "motorboat:02",
    "title": "2/16 · Samma båt",
    "image": "/assets/village/story-moments/act2/motorboat/01-finally-the-boat.png",
    "body": [
      "När ni går igenom båten upptäcker Barnet en detalj på sidan.",
      "Barnet: Vänta.",
      "Alve: Vad?",
      "Barnet: Har inte jag sett den där förut?",
      "Alve: Båten?",
      "Barnet: Nej, den där.",
      "Du pekar på ett gammalt märke i sidan.",
      "Alve böjer sig ner.",
      "Alve: Jag vet inte.",
      "Barnet: Fotot.",
      "Alve: Vilket foto?",
      "Du tittar på honom.",
      "Barnet: Det vi hittade i båthuset.",
      "Alve: Just det.",
      "Barnet: Det som du tittade på jättelänge.",
      "Alve: Jag tittade normalt länge.",
      "Ni tar fram det gamla fotografiet och jämför.",
      "Alve blir tyst.",
      "Barnet: Det är samma märke.",
      "Alve: Ja.",
      "Barnet: Så det är samma båt.",
      "Alve håller fotot bredvid båten.",
      "Alve: Det är den.",
      "Barnet: Din familjs båt.",
      "Alve: Mm.",
      "Han tittar på människorna på fotografiet och sedan på båten framför sig.",
      "Barnet: Kommer du ihåg när ni åkte med den?",
      "Alve: Lite.",
      "Barnet: Vart åkte ni?",
      "Alve tänker.",
      "Alve: Ut på sjön.",
      "Barnet: Det förstod jag.",
      "Alve: Jag var liten.",
      "Barnet: Det har vi också förstått.",
      "Alve: Jag minns mest ljudet.",
      "Barnet: Motorn?",
      "Alve: Mm. Och vinden.",
      "Han kisar mot fotot.",
      "Alve: Och att man inte fick stå upp.",
      "Barnet: Gjorde du det ändå?",
      "Alve tittar på honom.",
      "Alve: Jag börjar ångra att jag berättat saker för dig.",
      "Barnet: Så ja.",
      "Alve: Kanske.",
      "Du tittar på fotografiet igen.",
      "Barnet: Det är lite konstigt.",
      "Alve: Vadå?",
      "Barnet: Först var den bara en gammal båt.",
      "Alve: Och nu?",
      "Barnet: Nu vet vi att den varit någonstans.",
      "Alve tittar ut genom båthusöppningen över sjön.",
      "Alve: Ja.",
      "Barnet: Och du vet inte vart.",
      "Alve: Nej.",
      "Paus.",
      "Alve: Än."
    ],
    "stage": 1
  },
  {
    "id": "motorboat:03",
    "title": "3/16 · Linus känner igen den",
    "image": "/assets/village/story-moments/act2/motorboat/02-linus-inspects-the-boat.png",
    "body": [
      "Linus kommer ner till båthuset för att titta på projektet.",
      "Han går ett varv runt båten utan att säga något.",
      "Alve: Nå?",
      "Linus: Den är gammal.",
      "Alve: Det visste vi.",
      "Linus: Den har stått länge.",
      "Alve: Det visste vi också.",
      "Linus: Den är i sämre skick än du hoppas.",
      "Alve tittar på dig.",
      "Alve: Han gör så här med flit.",
      "Barnet: Jag tror det.",
      "Linus böjer sig ner och tittar på några av de gamla delarna ni hittade i båthuset.",
      "Linus: Men allt är inte skräp.",
      "Alve lyser upp.",
      "Alve: Så den går att laga?",
      "Linus: Jag sa inte det.",
      "Alve: Linus.",
      "Linus ler lite.",
      "Linus: Ja. Jag tror det.",
      "Alve vänder sig direkt mot Barnet.",
      "Alve: Hörde du?",
      "Barnet: Jag står här.",
      "Alve: Han tror den går att laga.",
      "Linus: Om ni gör jobbet ordentligt.",
      "Alve: Den delen hörde jag mindre tydligt.",
      "Linus tittar på fotografiet.",
      "Linus: Var hittade ni den här?",
      "Barnet: I kistan.",
      "Linus granskar bilden.",
      "Alve: Känner du igen båten?",
      "Linus: Ja.",
      "Alve blir genast allvarligare.",
      "Alve: Vet du vart den åkte?",
      "Linus: Över sjön.",
      "Alve: Ja, men vart?",
      "Linus räcker tillbaka fotografiet.",
      "Linus: Det får ni väl ta reda på.",
      "Alve: Du vet.",
      "Linus: Jag vet att en sjö har två sidor.",
      "Alve: Det där är inte ett svar.",
      "Linus: Det var inte meningen heller.",
      "Du tittar på Alve.",
      "Barnet: Han är ganska bra på det här.",
      "Alve: Fruktansvärt bra.",
      "Linus pekar mot båten.",
      "Linus: Börja med båten framför er. Andra sidan finns kvar senare.",
      "Alve tittar ut över vattnet igen.",
      "Alve: Sen.",
      "Linus: Precis.",
      "Alve: Jag börjar verkligen ogilla det ordet."
    ],
    "stage": 1
  },
  {
    "id": "motorboat:04",
    "title": "4/16 · Inte idag",
    "image": "/assets/village/story-moments/act2/motorboat/02-linus-inspects-the-boat.png",
    "body": [
      "Ni har jobbat vidare med båten tillsammans med Linus. En del går att rädda, annat får bytas, och för första gången börjar den faktiskt se ut som något som skulle kunna bli en båt igen.",
      "Alve står med händerna i sidorna och granskar resultatet.",
      "Alve: Nu då?",
      "Linus: Nu vadå?",
      "Alve: Nu borde den väl nästan funka.",
      "Linus tittar på honom.",
      "Linus: Nej.",
      "Alve: Du behövde inte svara så snabbt.",
      "Linus: Jag visste svaret redan.",
      "Du tittar på båten.",
      "Barnet: Den ser mycket bättre ut.",
      "Alve: Exakt.",
      "Linus: Det är inte samma sak som att den fungerar.",
      "Alve: Du är väldigt dålig på att bygga upp stämningen.",
      "Linus: Jag försöker bygga en båt.",
      "Alve böjer sig ner och tittar på en av delarna ni sorterat.",
      "Alve: Den här sparar vi?",
      "Linus: Ja.",
      "Alve: Och den där?",
      "Linus: Nej.",
      "Alve: Varför inte?",
      "Linus: För att den är slut.",
      "Alve: Kan man inte laga den?",
      "Linus: Allt går inte att laga.",
      "Alve blir tyst en sekund.",
      "Alve: Det där låter väldigt vuxet.",
      "Linus: Det var inte meningen.",
      "Du håller upp en annan gammal del.",
      "Barnet: Den här då?",
      "Linus tittar.",
      "Linus: Den kan vi använda.",
      "Alve tar den direkt.",
      "Alve: Bra.",
      "Barnet: Du gillar den.",
      "Alve: Jag gillar saker vi slipper kasta.",
      "Linus: Då har du lärt dig något.",
      "Alve: Säg inte det till någon.",
      "Ni fortsätter en stund.",
      "Till slut backar Linus undan och tittar på båten.",
      "Linus: Det räcker för idag.",
      "Alve: Va?",
      "Linus: För idag.",
      "Alve: Men vi är ju igång.",
      "Linus: Precis.",
      "Alve: Det där är ett dåligt argument för att sluta.",
      "Linus börjar plocka ihop verktygen.",
      "Alve: Tror du den kommer funka?",
      "Linus tittar på båten.",
      "Linus: Inte idag.",
      "Alve suckar djupt.",
      "Alve: Alla säger så hela tiden.",
      "Barnet: Vadå?",
      "Alve: Inte idag.",
      "Du tittar på båten.",
      "Barnet: Då fortsätter vi imorgon.",
      "Alve tittar på dig. Sedan på båten.",
      "Alve: Okej.",
      "Paus.",
      "Alve: Men tidigt.",
      "Barnet: Hur tidigt?",
      "Alve: Jättetidigt.",
      "Linus: Nej.",
      "Alve: Du behöver verkligen sluta svara så snabbt."
    ],
    "stage": 2
  },
  {
    "id": "motorboat:05",
    "title": "5/16 · Det som saknas",
    "image": "/assets/village/story-moments/act2/motorboat/02-linus-inspects-the-boat.png",
    "body": [
      "Nästa gång ni fortsätter har Alve redan lagt ut delarna på golvet i små högar.",
      "Du stannar i dörren.",
      "Barnet: Vad har hänt här?",
      "Alve: Ordning.",
      "Barnet: Det där ser inte ut som ordning.",
      "Alve: Jo.",
      "Alve pekar.",
      "Alve: Bra saker.",
      "En annan hög.",
      "Alve: Dåliga saker.",
      "En tredje.",
      "Alve: Saker jag inte vet.",
      "Barnet: Det är den största högen.",
      "Alve: Jag är fortfarande i början.",
      "Linus kommer in och tittar på golvet.",
      "Linus: Vad är det här?",
      "Alve: System.",
      "Linus: Nej.",
      "Barnet: Jag sa nästan samma sak.",
      "Linus går igenom delarna och stannar vid en tom plats.",
      "Linus: Här har vi problemet.",
      "Alve: Vilket problem?",
      "Linus: Några av delarna till motorn är för slitna. De går inte att rädda.",
      "Alve: Kan vi hitta gamla?",
      "Linus: Inte sådana jag skulle sätta tillbaka i den här båten.",
      "Barnet: Så vad behöver vi?",
      "Linus: Ett reservdelspaket.",
      "Alve: Har du ett?",
      "Linus: Nej.",
      "Alve: Kan du göra ett?",
      "Linus: Nej.",
      "Alve: Du säger nej väldigt mycket idag.",
      "Linus: Mira kan få tag på ett.",
      "Alve tittar på dig.",
      "Alve: Lanthandeln?",
      "Barnet: Lanthandeln.",
      "Alve: Bra. Då går vi.",
      "Han börjar redan gå.",
      "Linus: Alve.",
      "Alve stannar.",
      "Alve: Vad?",
      "Linus: Ta reda på vad ni ska köpa först.",
      "Alve går tillbaka.",
      "Alve: Just det.",
      "Barnet: Bra plan.",
      "Alve: Jag hade nästan hela.",
      "Linus förklarar vad reservdelspaketet ska lösa.",
      "Du lyssnar. Alve nickar väldigt allvarligt.",
      "När Linus är klar blir det tyst.",
      "Barnet: Kommer du ihåg allt?",
      "Alve: Nej.",
      "Linus: Jag skriver ner det.",
      "Alve: Det var också min plan."
    ],
    "stage": 2
  },
  {
    "id": "motorboat:06",
    "title": "6/16 · Mira beställer två",
    "image": "/assets/village/story-moments/act2/motorboat/03-mira-spare-parts-order.png",
    "body": [
      "Ni kommer in till Mira med lappen från Linus.",
      "Mira läser den. Sedan läser hon den en gång till.",
      "Mira: Så ni tänker verkligen få igång den där gamla båten?",
      "Barnet: Ja.",
      "Mira: Och Alve är inblandad?",
      "Barnet: Ja.",
      "Mira tittar på Alve.",
      "Alve: Hej.",
      "Mira tittar tillbaka på beställningen.",
      "Mira: Jag beställer ett reservdelspaket.",
      "Alve: Bra.",
      "Mira: Och en extra av den viktigaste delen.",
      "Alve: Varför?",
      "Mira: För att du är inblandad.",
      "Du börjar skratta.",
      "Alve: Vad betyder ens det?",
      "Mira: Att jag har träffat dig.",
      "Alve: Jag tycker inte om vart det här samtalet är på väg.",
      "Mira lägger undan lappen.",
      "Mira: Det blir 200 SysselBux.",
      "Alve tittar på dig.",
      "Alve: Vi har råd, eller hur?",
      "Barnet: Ja.",
      "Alve: Bra. För jag har redan bestämt mig.",
      "Mira: Det märktes.",
      "Du betalar 200 SysselBux genom den auktoritativa story-item-köpsfunktionen.",
      "Mira gör klart beställningen.",
      "Mira: Det kommer inte göra båten färdig.",
      "Alve: Jag vet.",
      "Mira tittar på honom lite misstänksamt.",
      "Mira: Gör du?",
      "Alve: Ja.",
      "Mira: Och du tänker inte försöka starta den direkt?",
      "Alve blir tyst.",
      "Du tittar på honom.",
      "Mira tittar på honom.",
      "Alve: Vad räknas som direkt?",
      "Mira: Alve.",
      "Alve: Okej.",
      "Han tittar på dig.",
      "Alve: Inte direkt.",
      "Barnet: Det där lät inte särskilt pålitligt.",
      "Mira: Därför beställde jag två."
    ],
    "stage": 2
  },
  {
    "id": "motorboat:07",
    "title": "7/16 · Paketet kommer",
    "image": "/assets/village/story-moments/act2/motorboat/03-mira-spare-parts-order.png",
    "body": [
      "Nästa gång ni kommer till båthuset ligger ett paket på arbetsbänken.",
      "Alve stannar mitt i steget.",
      "Alve: Är det där…",
      "Barnet: Japp.",
      "Alve: Redan?",
      "Barnet: Mira sa att det skulle komma.",
      "Alve: Jag trodde vuxna sa så för att få barn att gå hem.",
      "Du går fram till paketet. Alve är redan bredvid dig.",
      "Barnet: Du tänker öppna det innan Linus kommer.",
      "Alve: Nej.",
      "Paus.",
      "Alve: Jag tänkte öppna det väldigt försiktigt innan Linus kommer.",
      "Barnet: Det är samma sak.",
      "Alve: Inte alls.",
      "Linus kommer in genom dörren. Han tittar på Alve. Sedan på paketet. Sedan på Alve igen.",
      "Linus: Nej.",
      "Alve: Jag har inte gjort något.",
      "Linus: Bra.",
      "Alve: Du kan inte säga nej i förväg.",
      "Linus: Jag börjar lära mig.",
      "Linus öppnar paketet tillsammans med er.",
      "Alve tittar ner i lådan.",
      "Alve: Det där ser mindre spännande ut än jag hade tänkt mig.",
      "Barnet: Vad hade du tänkt dig?",
      "Alve: Något mer… båtmotorigt.",
      "Linus: Det här är båtmotorigt.",
      "Alve: Det ser ut som en låda med saker.",
      "Linus: Det är ungefär vad reservdelar är.",
      "Ni börjar jobba. Linus visar vad som ska användas, men låter er göra så mycket som möjligt själva.",
      "Efter en stund lutar sig Alve tillbaka.",
      "Alve: Nu.",
      "Linus: Nej.",
      "Alve: Du vet inte ens vad jag skulle säga.",
      "Linus: Jo.",
      "Alve: Vad då?",
      "Linus: Att ni ska prova att starta den.",
      "Alve blir tyst.",
      "Barnet: Han börjar bli läskigt bra på dig.",
      "Alve: Det här är ett problem.",
      "Linus: Ni är inte klara.",
      "Alve: Men vi har satt dit de nya sakerna.",
      "Linus: Ja.",
      "Alve: Och den ser redo ut.",
      "Linus: Den ser mindre trasig ut.",
      "Alve: Det är nästan samma sak.",
      "Linus: Nej.",
      "Alve suckar.",
      "Alve: Vad ska vi göra då?",
      "Linus pekar mot resten av båten.",
      "Linus: Fortsätta.",
      "Alve tittar på dig.",
      "Alve: Det här projektet innehåller väldigt mycket fortsätta.",
      "Barnet: Det brukar projekt göra.",
      "Alve: Jag saknar delen där man är klar."
    ],
    "stage": 2
  },
  {
    "id": "motorboat:08",
    "title": "8/16 · Den lever",
    "image": "/assets/village/story-moments/act2/motorboat/04-the-engine-lives.png",
    "body": [
      "Ni har gjort klart det Linus ville att ni skulle göra. Båten står fortfarande säkert i båthuset.",
      "Alve har varit ovanligt tyst de senaste minuterna.",
      "Barnet: Nu tänker du väldigt högt utan att säga något.",
      "Alve: Jag väntar.",
      "Barnet: På vad?",
      "Alve tittar på Linus. Linus fortsätter kontrollera båten.",
      "Alve: På ett ord.",
      "Linus tittar upp.",
      "Linus: Okej.",
      "Alve stirrar på honom.",
      "Alve: Var det ordet?",
      "Linus: Ja.",
      "Alve: Får vi prova?",
      "Linus: Ja.",
      "Alve ser på dig.",
      "Alve: Han sa ja.",
      "Barnet: Jag hörde.",
      "Alve: Det händer aldrig.",
      "Linus: Vill ni prova eller vill ni prata om att ni får prova?",
      "Alve: Prova.",
      "Ni gör ett första försök.",
      "Ingenting händer.",
      "Alve stirrar på båten.",
      "Alve: Okej.",
      "Barnet: Okej?",
      "Alve: Den kanske behöver tänka.",
      "Linus: Båtar tänker inte.",
      "Alve: Det vet du inte.",
      "Ni provar igen.",
      "Fortfarande ingenting.",
      "Alve sjunker ihop lite.",
      "Alve: Det här var mindre dramatiskt än jag hade planerat.",
      "Barnet: Du hade planerat dramatik?",
      "Alve: Lite.",
      "Linus tittar lugnt på båten.",
      "Linus: En gång till.",
      "Ni försöker igen.",
      "Ett kort ljud hörs från motorn.",
      "Sedan tystnar den.",
      "Alve fryser till.",
      "Alve: Hörde du?!",
      "Barnet: Ja.",
      "Alve: DEN LEVER.",
      "Linus: Lugn.",
      "Alve: DEN LEVER LUGNT.",
      "Du börjar skratta.",
      "Linus: Den startade i ungefär en sekund.",
      "Alve: Det var en väldigt bra sekund.",
      "Barnet: En historisk sekund.",
      "Alve: Exakt.",
      "Linus försöker se sträng ut, men ler lite.",
      "Linus: Det är framsteg.",
      "Alve tittar på båten.",
      "Alve: Hörde du?",
      "Barnet: Nu pratar du med båten igen.",
      "Alve: Den förtjänar beröm.",
      "Alve klappar försiktigt på sidan.",
      "Alve: Bra jobbat.",
      "Barnet: Det var vi som jobbade.",
      "Alve: Vi kan också få beröm.",
      "Han håller upp handen. Du slår till den.",
      "Alve: Bra jobbat."
    ],
    "stage": 3
  },
  {
    "id": "motorboat:09",
    "title": "9/16 · Ner i vattnet",
    "image": "/assets/village/story-moments/act2/motorboat/05-launching-the-boat.png",
    "body": [
      "För första gången sedan ni började med motorbåten ska den lämna båthuset.",
      "Ni står vid slipen och tittar på den.",
      "Alve: Den ser nervös ut.",
      "Barnet: Det är en båt.",
      "Alve: Man kan se det på den.",
      "Barnet: Var?",
      "Alve pekar vagt.",
      "Alve: Där.",
      "Barnet: Övertygande.",
      "Linus står bredvid och håller upp en hand.",
      "Linus: Lugnt nu.",
      "Alve: Jag är lugn.",
      "Barnet: Du har sagt det ungefär fyra gånger.",
      "Alve: Det är för att jag är väldigt lugn.",
      "Ni hjälper till att få båten ner mot vattnet.",
      "När den till slut ligger i sjön blir Alve helt tyst.",
      "Du tittar på honom.",
      "Barnet: Vad?",
      "Alve: Den flyter.",
      "Barnet: Det är bra för en båt.",
      "Alve: Jag vet.",
      "Han går närmare kanten.",
      "Alve: Men den flyter faktiskt.",
      "Linus kontrollerar att allt ser bra ut.",
      "Linus: Det här är bara första testet.",
      "Alve: Ja.",
      "Linus: Ni åker inte långt.",
      "Alve: Nej.",
      "Linus: Ni gör inget dumt.",
      "Alve tittar på dig.",
      "Barnet: Titta inte på mig.",
      "Alve: Jag sa inget.",
      "Linus: Jag såg.",
      "Alve kliver försiktigt ner i båten. Du kliver efter.",
      "För ett ögonblick händer ingenting. Vattnet rör sig mjukt runt skrovet.",
      "Alve tittar tillbaka mot båthuset.",
      "Alve: Den har stått där inne jättelänge.",
      "Barnet: Mm.",
      "Alve: Och nu är den här.",
      "Barnet: I sjön.",
      "Alve: I sjön.",
      "Han ler.",
      "Alve: Det känns som att det borde vara musik.",
      "Barnet: Vill du sjunga?",
      "Alve: Absolut inte.",
      "Linus ropar från land.",
      "Linus: Redo?",
      "Alve tittar på dig.",
      "Alve: Redo?",
      "Barnet: Japp.",
      "Alve tar ett djupt andetag.",
      "Alve: Okej.",
      "Han tittar på båten.",
      "Alve: Nu får du visa vad du kan."
    ],
    "stage": 3
  },
  {
    "id": "motorboat:10",
    "title": "10/16 · Första turen",
    "image": "/assets/village/story-moments/act2/motorboat/06-first-test-stall.png",
    "body": [
      "Motorn går. Inte bara ett hostande ljud den här gången. Den går faktiskt.",
      "Alve stirrar på den som om han inte riktigt litar på vad han hör.",
      "Alve: Den går.",
      "Barnet: Japp.",
      "Alve: Den går fortfarande.",
      "Barnet: Japp.",
      "Alve: Vi borde kanske säga något mer.",
      "Barnet: Kör?",
      "Alve tittar upp.",
      "Alve: Kör.",
      "Ni lämnar bryggan långsamt.",
      "Linus står kvar på land med armarna i kors.",
      "Alve tittar bakåt.",
      "Alve: Vi åker.",
      "Barnet: Det brukar hända när man kör båt.",
      "Alve: Nej, men vi åker.",
      "Du tittar tillbaka mot bryggan. Den blir sakta mindre.",
      "Barnet: Vi har faktiskt lämnat land.",
      "Alve: Jag vet.",
      "Paus.",
      "Alve: Det här är fantastiskt.",
      "Ni kommer en liten bit ut.",
      "Alve håller blicken framåt.",
      "Alve: Tror du vi kan åka längre?",
      "Barnet: Linus sa inte långt.",
      "Alve: Det här är inte långt.",
      "Barnet: Än.",
      "Alve ler.",
      "Sedan hostar motorn.",
      "Alve slutar le.",
      "Alve: Nej.",
      "Motorn hostar igen.",
      "Alve: Nej nej nej.",
      "Den stannar.",
      "Tystnad.",
      "Båten glider sakta vidare en liten bit.",
      "Barnet: Den stannade.",
      "Alve: Jag märkte det.",
      "Barnet: Vill du att jag säger att det gick ganska bra?",
      "Alve: Inte än.",
      "Från bryggan hörs Henning ropa.",
      "Henning: GÅR DET BRA?",
      "Alve: JAPP!",
      "Du tittar på honom.",
      "Barnet: Det gör det inte.",
      "Alve: DET GÅR GANSKA BRA!",
      "Henning vinkar glatt.",
      "Barnet: Varför sa du så?",
      "Alve: För att det gick väldigt bra precis innan det slutade gå bra.",
      "Du börjar skratta. Alve gör det också.",
      "Alve: Vi kom i alla fall ut.",
      "Barnet: Och nu ska vi tillbaka.",
      "Alve: Detaljer."
    ],
    "stage": 3
  },
  {
    "id": "motorboat:11",
    "title": "11/16 · Tillbaka igen",
    "image": "/assets/village/story-moments/act2/motorboat/06-first-test-stall.png",
    "body": [
      "Efter en stund får ni hjälp tillbaka till bryggan.",
      "Alve hoppar iland.",
      "Henning: Det såg väldigt bra ut.",
      "Barnet: Tills det inte gjorde det.",
      "Henning: Jag tittade mest i början.",
      "Alve: Bra val.",
      "Linus kommer fram.",
      "Linus: Hur gick det?",
      "Alve: Perfekt.",
      "Du tittar på honom.",
      "Alve: Nästan perfekt.",
      "Linus tittar på dig.",
      "Barnet: Vi kom ungefär dit.",
      "Du pekar ut över vattnet.",
      "Linus: Och sen?",
      "Barnet: Sen slutade den gå.",
      "Alve: Men innan dess gick den.",
      "Linus: Det är därför man testar.",
      "Alve: Jag trodde test betydde att man skulle se om den fungerade.",
      "Linus: Det gjorde ni.",
      "Alve: Och?",
      "Linus tittar på båten.",
      "Linus: Den fungerar.",
      "Alve lyser upp.",
      "Linus: Inte tillräckligt bra än.",
      "Alve sjunker ihop igen.",
      "Alve: Du borde verkligen lägga till hela meningen direkt.",
      "Henning tittar ner i båten.",
      "Henning: Behöver ni hjälp?",
      "Alve: Kan du laga båtmotorer?",
      "Henning: Nej.",
      "Alve: Då är svaret lite oklart.",
      "Henning: Jag kan ta med fika.",
      "Alve tänker.",
      "Alve: Okej. Du är med.",
      "Linus skakar på huvudet.",
      "Ni börjar gå igenom vad som återstår.",
      "Den här gången låter Alve inte lika otålig.",
      "Barnet: Du försöker inte starta den igen.",
      "Alve: Nej.",
      "Barnet: Är du sjuk?",
      "Alve: Jag tänkte vänta tills vi vet varför den stannade.",
      "Linus tittar upp.",
      "Linus: Bra.",
      "Alve ser genast irriterad ut.",
      "Alve: Säg inte det så där.",
      "Linus: Hur då?",
      "Alve: Som att jag lär mig saker."
    ],
    "stage": 3
  },
  {
    "id": "motorboat:12",
    "title": "12/16 · Vår båt",
    "image": "/assets/village/story-moments/act2/motorboat/07-our-boat.png",
    "body": [
      "Efter ännu mer arbete står motorbåten vid bryggan igen.",
      "Den ser färdig ut nu. Inte ny, men hel. Användbar. Er.",
      "Sol har lämnat säkerhetsutrustning. Mira har fixat det praktiska ni saknade. Henning har lyckats ställa en alldeles för stor påse fika i båten.",
      "Alve tittar ner i den.",
      "Alve: Varför är det så mycket mat?",
      "Barnet: Henning.",
      "Alve: Det svarade faktiskt på frågan.",
      "Linus går ett sista varv runt båten.",
      "Alve: Nu är den klar.",
      "Linus: Nej.",
      "Alve snurrar runt.",
      "Alve: VA?",
      "Linus: Ni har inte provat om den håller hela vägen.",
      "Alve: Vi har ju kört den.",
      "Linus: En liten bit.",
      "Barnet: Och blivit hämtade.",
      "Alve: Det behöver vi inte ta upp varje gång.",
      "Linus klappar på relingen.",
      "Linus: Den ser klar ut.",
      "Alve: Bra.",
      "Linus: Nu ska ni bevisa att den är det.",
      "Alve suckar, men ler samtidigt.",
      "Alve: Okej.",
      "Han går runt båten och stannar vid sidan.",
      "Alve: Den behöver ett namn.",
      "Barnet: Gör den?",
      "Alve: Alla bra båtar har namn.",
      "Barnet: Hur många båtar känner du?",
      "Alve: Det är inte viktigt.",
      "Du tittar på båten.",
      "Barnet: Vad ska den heta då?",
      "Alve tänker länge.",
      "Alve: Jag vet inte.",
      "Barnet: Starkt.",
      "Alve: Det måste vara bra.",
      "Barnet: Jag kan döpa den.",
      "Alve tittar på dig.",
      "Alve: Okej.",
      "Alve: Men välj något bra.",
      "Barnet: Ingen press.",
      "Alve: Jättemycket press."
    ],
    "stage": 4
  },
  {
    "id": "motorboat:13",
    "title": "13/16 · Det riktiga testet",
    "image": "/assets/village/story-moments/act2/motorboat/08-ready-for-the-real-test.png",
    "body": [
      "Nästa gång ni kommer ner till bryggan står båten redo. Alve går igenom sakerna ombord en efter en.",
      "Barnet: Vad gör du egentligen?",
      "Alve: Kontrollerar allt. Jag har lärt mig att om man missar något så dyker Linus upp och kontrollerar det åt en ändå, så jag försöker ligga före.",
      "Linus kommer gående bakom er.",
      "Linus: Bra tänkt.",
      "Alve suckar.",
      "Alve: Där är han.",
      "Sol lämnar säkerhetsutrustningen i båten.",
      "Sol: Det här ska med. Ni har kommit långt, men en fungerande båt betyder också att man måste vara lite smartare än när den bara står på land.",
      "Alve: Vi har redan grejer.",
      "Sol: Nu har ni rätt grejer.",
      "Mira räcker över en liten påse.",
      "Mira: Och det här är sådant ni kommer önska att ni tog med om något litet strular. Inte spännande, men väldigt bra att ha.",
      "Alve: Det där lät misstänkt genomtänkt.",
      "Mira: Därför får du inte packa upp det och börja använda saker på måfå.",
      "Henning kommer med en betydligt större påse.",
      "Barnet: Det där är inte säkerhetsutrustning.",
      "Henning: Nej, det är viktigare. Färdkost.",
      "Barnet: Vi ska testa båten, inte korsa Atlanten.",
      "Henning: Man vet aldrig hur hungrig man blir av att nästan korsa Atlanten.",
      "Alve nickar uppskattande.",
      "Alve: Äntligen någon som planerar ordentligt.",
      "Linus går ett sista varv runt båten.",
      "Linus: Ni har det ni behöver. Ni har gått igenom båten. Ni vet hur långt ni ska köra och när ni ska vända. Så, redo?",
      "Alve: Japp.",
      "Barnet: Japp.",
      "Linus nickar.",
      "Linus: Bra. Då behöver ni inte mig.",
      "Alve tittar på honom.",
      "Alve: Vänta. Ska du inte följa med?",
      "Linus: Nej. Hela poängen med testet är att ni ska visa att ni kan använda båten själva. Jag finns kvar här om något händer, men ni behöver inte ha en vuxen bredvid er för varje steg.",
      "Alve tittar på båten igen.",
      "Alve: Det här känns mycket större än det gjorde för fem minuter sen.",
      "Barnet: Du ville ju köra.",
      "Alve: Jag vill fortfarande köra. Jag vill bara att du också ska vilja det.",
      "Barnet: Jag sitter redan i båten.",
      "Alve ler.",
      "Alve: Bra svar."
    ],
    "stage": 4
  },
  {
    "id": "motorboat:14",
    "title": "14/16 · Vi åker båt",
    "image": "/assets/village/story-moments/act2/motorboat/09-we-ride-boat.png",
    "body": [
      "Motorn startar utan att tveka. Ni lämnar bryggan och glider ut över sjön.",
      "En stund säger ingen någonting.",
      "Du tittar tillbaka på stugan, bryggan och båthuset.",
      "Alve: Det ser nästan konstigt ut härifrån. När vi började var allt trasigt eller tomt, och nu ser det ut som om det alltid har varit så här.",
      "Barnet: Fast vi vet hur det såg ut.",
      "Alve: Ja. Det är nog därför det känns så konstigt.",
      "Han pekar tillbaka mot land.",
      "Alve: Bryggan höll nästan på att falla sönder. Båthuset gick knappt att använda. Stugan var tom. Och båten stod bara där inne och blev äldre.",
      "Barnet: Nu används allt.",
      "Alve: Ja.",
      "Han blir tyst och tittar framåt.",
      "Alve: {childName}.",
      "Barnet: Mm?",
      "Alve: Vi åker faktiskt båt.",
      "Barnet: Det var ju planen.",
      "Alve: Jag vet. Men det är skillnad på att planera något och att plötsligt vara mitt ute på sjön i båten man har lagat själv.",
      "Du ler.",
      "Barnet: Vår båt.",
      "Alve: Ja. Vår båt.",
      "Ni fortsätter längs er sida av sjön.",
      "Alve: Jag undrar hur långt den klarar egentligen.",
      "Barnet: Vi ska inte ta reda på allt idag.",
      "Alve tittar mot andra sidan. Du märker det direkt.",
      "Barnet: Jag såg den där blicken.",
      "Alve: Vilken blick?",
      "Barnet: Den som betyder att du funderar på att bara fortsätta tills någon stoppar dig.",
      "Alve skrattar.",
      "Alve: Okej. Jag tänkte lite så.",
      "Sedan tittar han framåt igen.",
      "Alve: Men inte idag.",
      "Du tittar på honom.",
      "Barnet: Det där var oväntat.",
      "Alve: Jag lär mig faktiskt saker ibland.",
      "Barnet: Säg inte det högt. Linus kanske hör dig från land."
    ],
    "stage": 4
  },
  {
    "id": "motorboat:15",
    "title": "15/16 · Inte idag",
    "image": "/assets/village/story-moments/act2/motorboat/09-we-ride-boat.png",
    "body": [
      "Ni har kommit längre bort än under något tidigare test. Motorn går jämnt.",
      "Sedan hörs ett klonk bakom er.",
      "Alve börjar resa sig direkt.",
      "Barnet: Vänta. Båten först.",
      "Han stannar och sätter sig igen.",
      "Alve: Just det. Först ser vi till att inget händer, sen fixar vi grejen.",
      "Tillsammans ordnar ni det som lossnat utan dramatik.",
      "Efteråt lutar sig Alve tillbaka.",
      "Alve: Det där gick faktiskt ganska bra.",
      "Barnet: Ja. Du kastade dig inte på problemet direkt.",
      "Alve: Jag tänkte göra det.",
      "Barnet: Det märktes.",
      "Alve: Men jag gjorde det inte.",
      "Barnet: Det är framsteg.",
      "Alve ser misstänksam ut.",
      "Alve: Du börjar låta som Linus.",
      "Ni fortsätter till platsen där ni bestämt att ni ska vända.",
      "Den andra sidan av sjön ligger framför er.",
      "Alve blir tyst.",
      "Barnet: Du tänker på den.",
      "Alve: Ja.",
      "Han tittar över vattnet.",
      "Alve: Vi skulle kunna fortsätta. Båten fungerar, vi har allt med oss och vi har till och med Hennings katastrofmängd mat.",
      "Barnet: Det skulle vi.",
      "Alve tittar på dig.",
      "Barnet: Men inte idag.",
      "Alve säger inget först. Sedan nickar han.",
      "Alve: Inte idag.",
      "Paus.",
      "Barnet: Du brukar hata de orden.",
      "Alve tittar mot andra sidan.",
      "Alve: Ja. Men jag tror jag fattar dem bättre nu. ‘Inte idag’ betyder ju inte att man aldrig kommer dit.",
      "Barnet: Precis.",
      "Alve vänder båten tillbaka.",
      "Efter en stund syns stugan igen långt borta.",
      "Alve: Då åker vi hem.",
      "Du tittar på honom.",
      "Barnet: Hem?",
      "Alve följer din blick mot stugan.",
      "Sedan svarar han mycket enklare.",
      "Alve: Ja."
    ],
    "stage": 4
  },
  {
    "id": "motorboat:16",
    "title": "16/16 · Hem igen",
    "image": "/assets/village/story-moments/act2/motorboat/10-home-again.png",
    "body": [
      "Båten glider tillbaka mot bryggan.",
      "Den här gången stannar den inte. Inget hostar, inget lossnar och ingen behöver komma och hämta er.",
      "Alve sitter tyst en stund och tittar mot land.",
      "Alve: Det känns nästan konstigt att allt bara fungerar nu. Förut hann man knappt bli glad innan något gick sönder igen.",
      "Barnet: Vi har väl blivit bättre på att laga saker.",
      "Alve: Eller bättre på att inte förstöra dem direkt.",
      "När ni närmar er bryggan står de andra där och väntar.",
      "Alve: Jag tänker säga att hela turen gick perfekt.",
      "Barnet: Även delen där grejerna lossnade?",
      "Alve: Den delen var en övning i problemlösning.",
      "Ni lägger till.",
      "Linus tittar först på båten och sedan på er.",
      "Linus: Ni kom tillbaka själva, båten är hel och motorn går fortfarande. Det får räknas som ett godkänt test.",
      "Alve tittar misstänksamt på honom.",
      "Alve: Det kommer inget ‘men’?",
      "Linus: Nej.",
      "Alve väntar lite.",
      "Alve: Det där kändes nästan läskigare.",
      "Linus ler.",
      "Linus: Bra jobbat.",
      "Valpen springer fram och nosar direkt på Hennings matsäck.",
      "Alve: Vi har varit ute på sjön och bevisat att båten fungerar, och han bryr sig om mackor.",
      "Henning: Han förstår vad som är viktigt.",
      "Sol tittar på båten.",
      "Sol: Hur kändes den?",
      "Alve ser tillbaka över sjön.",
      "Alve: Som att den inte längre är den gamla båten vi hittade i båthuset.",
      "Han lägger handen på relingen.",
      "Alve: Nu är den vår.",
      "Du tittar på båten.",
      "Barnet: Det är den.",
      "Alve ler.",
      "Alve: Så då är vi klara?",
      "Linus nickar.",
      "Linus: Med båten, ja.",
      "Alve tittar på dig.",
      "Alve: Jag tar det."
    ],
    "stage": 4
  }
];

export const MOTORBOAT_PARTS_PRICE = 200;
